---
- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    packages:
      - sudo
      - acl
      - vim

- name: Make sure ssh agent forwarding works
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: SSH_AUTH_SOCK
    line: Defaults env_keep+=SSH_AUTH_SOCK

- name: Ensure the correct locale is set
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - fr_FR.UTF-8
    - en_US.UTF-8
