---
- name: Install required packages
  apt: state=latest name={{ item }} update_cache=true
  with_items:
    - sudo
    - acl

- name: Make sure ssh agent forwarding works
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: SSH_AUTH_SOCK
    line: Defaults env_keep+=SSH_AUTH_SOCK
