---
- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    packages:
      - sudo
      - acl
      - vim

- name: Make sure ssh agent forwarding works
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: SSH_AUTH_SOCK
    line: Defaults env_keep+=SSH_AUTH_SOCK

- name: Make sure the ssh server is secure
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart sshd

- name: Configure the /etc/motd file, printed upon ssh login
  template:
    src: motd.j2
    dest: /etc/motd

- name: Ensure the correct locale is set
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - fr_FR.UTF-8
    - en_US.UTF-8

- name: Make sure the root prompt is readable enough
  lineinfile:
    path: /root/.bashrc
    state: present
    regexp: "^PS1="
    insertafter: EOF
    line: "{{ shell_prompt }}"
