# Generated by Django 2.2.17 on 2020-12-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_event_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.CharField(default="", max_length=256, verbose_name="Source"),
        ),
    ]
