# Generated by Django 3.1.6 on 2021-02-15 17:22

from django.db import migrations


def copy_data_from_event_table(apps, schema_editor):
    Aid = apps.get_model('aids', 'Aid')
    Event = apps.get_model('stats', 'Event')
    AidViewEvent = apps.get_model('stats', 'AidViewEvent')

    all_aids = Aid.objects.all()
    events = Event.objects.filter(category='aid', event='viewed')
    
    aid_view_events_to_created = []
    event_ids_to_delete = []
    for event in events:
        try:
            aid = all_aids.get(slug=aid_view_event.meta)
            aid_view_event = AidViewEvent(
                aid=aid,
                source=aid_view_event.source,
                date_created=date_created)
            aid_view_events_to_created.append(aid_view_event)
            event_ids_to_delete.append(event.id)
        except:
            pass
    
    AidViewEvent.objects.bulk_create(aid_view_events_to_created)
    Event.objects.filter(id__in=event_ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_aidviewevent'),
    ]

    operations = [
        migrations.RunPython(copy_data_from_event_table)
    ]
