# Generated by Django 3.1.7 on 2021-03-02 18:37

from django.db import migrations

from search.utils import get_querystring_backers


def populate_aidsearchevent_backers(apps, schema_editor):
    AidSearchEvent = apps.get_model("stats", "AidSearchEvent")
    for event in AidSearchEvent.objects.all():
        event_backers = get_querystring_backers(event.querystring)
        event_backers_id_list = [backer.id for backer in event_backers]
        event.backers.set(event_backers_id_list)


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0011_aidsearchevent_backers"),
    ]

    operations = [migrations.RunPython(populate_aidsearchevent_backers)]
