# Generated by Django 3.1.7 on 2021-04-06 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0124_aid_projects'),
        ('projects', '0003_auto_20210318_1456'),
        ('stats', '0015_auto_20210318_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidMatchProjectEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aids.aid', verbose_name='Aid')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Aid Match Project Event',
                'verbose_name_plural': 'Aid Match Project Events',
            },
        ),
    ]
