# Generated by Django 3.1.8 on 2021-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_aidmatchprojectevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidmatchprojectevent',
            name='is_matching',
            field=models.BooleanField(default=False, help_text='If the project match the aid', verbose_name='Is the project match the aid?'),
        ),
        migrations.AddField(
            model_name='aidmatchprojectevent',
            name='querystring',
            field=models.TextField(default='', verbose_name='Querystring'),
        ),
        migrations.AddField(
            model_name='aidmatchprojectevent',
            name='source',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Source'),
        ),
    ]
