# Generated by Django 3.1.8 on 2021-04-27 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert_source'),
        ('stats', '0016_aidmatchprojectevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertFeedbackEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(verbose_name='Feedback rate')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alert', verbose_name='Alert')),
            ],
            options={
                'verbose_name': 'Alert feedback event',
                'verbose_name_plural': 'Alert feedback events',
            },
        ),
    ]
