# Generated by Django 3.1.8 on 2021-05-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_aidviewevent_targeted_audiences'),
        ('stats', '0017_alertfeedbackevent'),
    ]

    operations = [
    ]
