# Generated by Django 3.2 on 2021-05-05 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0129_auto_20210413_1118"),
        ("stats", "0018_aidviewevent_targeted_audiences"),
    ]

    operations = [
        migrations.CreateModel(
            name="AidContactClickEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "querystring",
                    models.TextField(default="", verbose_name="Querystring"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Source"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date created"
                    ),
                ),
                (
                    "aid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aids.aid",
                        verbose_name="Aid",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement aide voir les contacts",
                "verbose_name_plural": "Événements aide voir les contacts",
            },
        ),
    ]
