# Generated by Django 3.2.2 on 2021-05-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_aidcontactclickevent'),
        ('stats', '0019_merge_20210503_1004'),
    ]

    operations = [
    ]
