# Generated by Django 3.2.4 on 2021-07-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0144_alter_aid_targeted_audiences'),
        ('stats', '0024_auto_20210708_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidcontactclickevent',
            name='aid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aids.aid', verbose_name='Aid'),
        ),
        migrations.AlterField(
            model_name='aideligibilitytestevent',
            name='aid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aids.aid', verbose_name='Aid'),
        ),
        migrations.AlterField(
            model_name='aidviewevent',
            name='aid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aids.aid', verbose_name='Aid'),
        ),
    ]
