# Generated by Django 3.2.16 on 2022-12-02 09:53

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_theme_short_description'),
        ('aids', '0169_alter_aid_status'),
        ('programs', '0011_auto_20221123_1400'),
        ('blog', '0006_textfield_image_promotion'),
        ('eligibility', '0004_eligibilitytest_conclusions'),
        ('geofr', '0040_perimeterdata_squashed_0042_alter_perimeterdata_unique_together'),
        ('backers', '0015_backer_perimeter'),
        ('stats', '0028_aidapplicationurlclickevent_aidoriginurlclickevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRegisterFromNextpagewarningClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querystring', models.TextField(default='', verbose_name='Querystring')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Événement compte clic sur le bouton Register-from-Next-Page-Warning',
                'verbose_name_plural': 'Événements compte clic sur le bouton Register-from-Next-Page-Warning',
            },
        ),
        migrations.AlterModelOptions(
            name='aidsearchevent',
            options={'verbose_name': 'Événement recherche d’aides', 'verbose_name_plural': 'Événements recherche d’aides'},
        ),
        migrations.AlterModelOptions(
            name='aidviewevent',
            options={'verbose_name': 'Événement aide vue', 'verbose_name_plural': 'Événement aides vues'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterField(
            model_name='aidapplicationurlclickevent',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aids.aid', verbose_name='Aide'),
        ),
        migrations.AlterField(
            model_name='aidapplicationurlclickevent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='aidcontactclickevent',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aids.aid', verbose_name='Aide'),
        ),
        migrations.AlterField(
            model_name='aidcontactclickevent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='aideligibilitytestevent',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aids.aid', verbose_name='Aide'),
        ),
        migrations.AlterField(
            model_name='aideligibilitytestevent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='aideligibilitytestevent',
            name='eligibility_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eligibility.eligibilitytest', verbose_name='Test d’éligibilité'),
        ),
        migrations.AlterField(
            model_name='aidoriginurlclickevent',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aids.aid', verbose_name='Aide'),
        ),
        migrations.AlterField(
            model_name='aidoriginurlclickevent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='aidsearchevent',
            name='backers',
            field=models.ManyToManyField(blank=True, related_name='aid_search_events', to='backers.Backer', verbose_name='Porteurs d’aides'),
        ),
        migrations.AlterField(
            model_name='aidsearchevent',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='aid_search_events', to='categories.Category', verbose_name='Sous-thématiques'),
        ),
        migrations.AlterField(
            model_name='aidsearchevent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='aidsearchevent',
            name='perimeter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='geofr.perimeter', verbose_name='Périmètre'),
        ),
        migrations.AlterField(
            model_name='aidsearchevent',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='aid_search_events', to='programs.Program', verbose_name='Programmes'),
        ),
        migrations.AlterField(
            model_name='aidsearchevent',
            name='results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de résultats'),
        ),
        migrations.AlterField(
            model_name='aidsearchevent',
            name='targeted_audiences',
            field=core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('commune', 'Communes'), ('epci', 'Intercommunalités / Pays'), ('department', 'Départements'), ('region', 'Régions'), ('special', "Collectivités d'outre-mer à statuts particuliers"), ('association', 'Associations'), ('private_person', 'Particuliers'), ('farmer', 'Agriculteurs'), ('private_sector', 'Entreprises privées'), ('public_cies', 'Entreprises publiques locales (Sem, Spl, SemOp)'), ('public_org', "Établissements publics (écoles, bibliothèques…) / Services de l'État"), ('researcher', 'Recherche')], max_length=32), blank=True, null=True, size=None, verbose_name='Bénéficiaires de l’aide'),
        ),
        migrations.AlterField(
            model_name='aidsearchevent',
            name='text',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Recherche textuelle'),
        ),
        migrations.AlterField(
            model_name='aidsearchevent',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='aid_search_events', to='categories.Theme', verbose_name='Thématiques'),
        ),
        migrations.AlterField(
            model_name='aidviewevent',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aids.aid', verbose_name='Aide'),
        ),
        migrations.AlterField(
            model_name='aidviewevent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='aidviewevent',
            name='targeted_audiences',
            field=core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('commune', 'Communes'), ('epci', 'Intercommunalités / Pays'), ('department', 'Départements'), ('region', 'Régions'), ('special', "Collectivités d'outre-mer à statuts particuliers"), ('association', 'Associations'), ('private_person', 'Particuliers'), ('farmer', 'Agriculteurs'), ('private_sector', 'Entreprises privées'), ('public_cies', 'Entreprises publiques locales (Sem, Spl, SemOp)'), ('public_org', "Établissements publics (écoles, bibliothèques…) / Services de l'État"), ('researcher', 'Recherche')], max_length=32), blank=True, null=True, size=None, verbose_name='Bénéficiaires de l’aide'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=128, verbose_name='Sous-thématique'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=128, verbose_name='Événement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta',
            field=models.CharField(default='', max_length=256, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='event',
            name='value',
            field=models.IntegerField(verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='promotionclickevent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='promotionclickevent',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.promotionpost', verbose_name='Communication promotionnelle'),
        ),
        migrations.AlterField(
            model_name='promotiondisplayevent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='promotiondisplayevent',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.promotionpost', verbose_name='Communication promotionnelle'),
        ),
    ]
