# Generated by Django 4.1.5 on 2023-02-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0029_auto_20221202_1053"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aidoriginurlclickevent",
            options={
                "verbose_name": "Événement aide plus d’informations",
                "verbose_name_plural": "Événements aide plus d'informations",
            },
        ),
    ]
