# Generated by Django 4.1.5 on 2023-02-21 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0030_alter_aidoriginurlclickevent_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormSendEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            (None, "----"),
                            (
                                "contact_add",
                                "Je veux en savoir plus sur l’ajout de mes aides sur la plateforme",
                            ),
                            (
                                "contact_com",
                                "Je souhaite communiquer sur Aides-territoires",
                            ),
                            (
                                "contact_question",
                                "J’ai une question sur mon compte utilisateur",
                            ),
                            ("contact_blog", "J’ai une question concernant le blog"),
                            (
                                "contact_api",
                                "Je souhaite utiliser les données d’Aides-territoires / API",
                            ),
                            ("contact_tech", "J'ai un problème technique sur le site"),
                            (
                                "contact_fonds_vert",
                                "J’ai une question sur le fonds vert",
                            ),
                            ("contact_other", "Autres"),
                        ],
                        max_length=256,
                        verbose_name="Sujet de l'email",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement envoi du formulaire de contact",
                "verbose_name_plural": "Événements envoi du formulaire de contact",
            },
        ),
    ]
