# Generated by Django 4.1.5 on 2023-02-21 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0030_alter_aidoriginurlclickevent_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormSendEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=256, verbose_name="Subject")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement envoi du formulaire de contact",
                "verbose_name_plural": "Événements envoi du formulaire de contact",
            },
        ),
    ]
