# Generated by Django 4.1.7 on 2023-04-14 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0013_organization_density_typology_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0034_aidcreatedsfolderevent_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidsearchevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.organization",
                verbose_name="Structure",
            ),
        ),
        migrations.AddField(
            model_name="aidsearchevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
