# Generated by Django 4.1.7 on 2023-04-17 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_alter_project_due_date_and_more"),
        ("organizations", "0013_organization_density_typology_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0035_aidsearchevent_organization_aidsearchevent_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicProjectViewEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                        verbose_name="Structure",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="Projet public",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement projet public vu",
                "verbose_name_plural": "Événements projet public vu",
            },
        ),
    ]
