# Generated by Django 4.1.7 on 2023-04-17 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("geofr", "0044_perimeter_density_typology_perimeter_insee_and_more"),
        ("organizations", "0013_organization_density_typology_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0036_publicprojectviewevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidatedProjectSearchEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Recherche textuelle",
                    ),
                ),
                ("querystring", models.TextField(verbose_name="Querystring")),
                (
                    "results_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de résultats"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                        verbose_name="Structure",
                    ),
                ),
                (
                    "perimeter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="geofr.perimeter",
                        verbose_name="Périmètre",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement recherche projets subventionnés",
                "verbose_name_plural": "Événements recherche projets subventionnés",
            },
        ),
    ]
