# Generated by Django 4.1.7 on 2023-04-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0013_organization_density_typology_and_more"),
        ("backers", "0015_backer_perimeter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0039_programviewevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programviewevent",
            options={
                "verbose_name": "Événement programme vu",
                "verbose_name_plural": "Événements programmes vus",
            },
        ),
        migrations.CreateModel(
            name="BackerViewEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(default="", max_length=256, verbose_name="Source"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "backer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backers.backer",
                        verbose_name="Porteur",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                        verbose_name="Structure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement porteur vu",
                "verbose_name_plural": "Événements porteurs vus",
            },
        ),
    ]
