# Generated by Django 4.1.5 on 2023-01-10 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("aid_team", "Notification aide structure"),
                            ("aid_user", "Notification aide personnelle"),
                            ("generic_team", "Notification générique structure"),
                            ("generic_user", "Notification générique personnelle"),
                        ],
                        default="generic_user",
                        help_text="Utilisé pour la gestion des préférences de réception des notifications",
                        max_length=32,
                        verbose_name="type de notification",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="titre")),
                ("message", models.CharField(max_length=500, verbose_name="message")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "date_read",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de consultation"
                    ),
                ),
                (
                    "date_email",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="date d’envoi de la notification par courriel",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "ordering": ["date_created"],
            },
        ),
    ]
