# Generated by Django 3.2.16 on 2022-12-08 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="titre")),
                ("message", models.CharField(max_length=500, verbose_name="message")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "date_read",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de consultation"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("account", "Compte utilisateur"),
                            ("aids", "Aides"),
                            ("projects", "Projets"),
                            ("other", "Autres"),
                        ],
                        default="others",
                        help_text="Utilisé pour la gestion des préférences de réception des notifications",
                        max_length=32,
                        verbose_name="type de notification",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Utilisé pour marquer comme lu",
                        unique=True,
                        verbose_name="clé secrète",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "ordering": ["date_created"],
            },
        ),
    ]
