# Generated by Django 3.2.16 on 2022-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="token",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("aid_team", "Notification aide structure"),
                    ("aid_user", "Notification aide personnelle"),
                    ("internal_team", "Notification interne structure"),
                    ("internal_user", "Notification interne personnelle"),
                ],
                default="internal_user",
                help_text="Utilisé pour la gestion des préférences de réception des notifications",
                max_length=32,
                verbose_name="type de notification",
            ),
        ),
    ]
