# Generated by Django 3.2.16 on 2022-11-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_read",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date de consultation"
            ),
        ),
    ]
