# Generated by Django 4.1.5 on 2023-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(verbose_name="message"),
        ),
    ]
