# Generated by Django 3.2.16 on 2023-01-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_auto_20221214_1551"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="date_email",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date d’envoi de la notification par courriel",
            ),
        ),
    ]
