# Generated by Django 2.2.7 on 2019-11-29 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70, verbose_name="Name")),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="Short description"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Themes",
                "verbose_name": "Theme",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70, verbose_name="Name")),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=160, verbose_name="Short description"
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories",
                        to="categories.Theme",
                        verbose_name="Theme",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "verbose_name": "Category",
            },
        ),
    ]
