# Generated by Django 4.2.3 on 2023-08-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0005_alter_theme_short_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Sous-thématique",
                "verbose_name_plural": "Sous-thématiques",
            },
        ),
        migrations.AlterModelOptions(
            name="theme",
            options={
                "verbose_name": "Thématique",
                "verbose_name_plural": "Thématiques",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=70, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="category",
            name="short_description",
            field=models.TextField(
                blank=True, max_length=160, verbose_name="Brève description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(verbose_name="Fragment d’URL"),
        ),
        migrations.AlterField(
            model_name="category",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="categories.theme",
                verbose_name="Thématique",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="name",
            field=models.CharField(max_length=70, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Brève description"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="slug",
            field=models.SlugField(verbose_name="Fragment d’URL"),
        ),
    ]
