dist: bionic
env:
  global:
    - LANG=fr_FR.UTF-8
    - LC_ALL=fr_FR.UTF-8
language: python
python:
  - "3.7"
addons:
  postgresql: "11"
  firefox: "latest"
  apt_packages:
    - language-pack-fr
before_install:
 - sudo update-locale LANG="fr_FR.UTF-8" LC_ALL="fr_FR.UTF-8"
 - locale
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
 - mkdir geckodriver
 - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
 - export PATH=$PATH:$PWD/geckodriver
 - cd $TRAVIS_BUILD_DIR/src
install:
 - npm install -g sass
 - make init
before_script:
  - psql --version
  - psql -c 'SELECT version();' -U postgres
  - psql -d template1 -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;' -U postgres
  - psql -c "CREATE USER aides WITH CREATEDB PASSWORD 'aides';" -U postgres
script:
 - make checkstyle
 - make test
