# Generated by Django 2.2.16 on 2020-09-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_auto_20190927_1021"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="perimeter",
        ),
    ]
