# Generated by Django 2.2.16 on 2020-09-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0004_auto_20200928_1547"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="aids",
        ),
    ]
