# Generated by Django 2.2.17 on 2020-12-07 12:41

from django.db import migrations, models
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0005_remove_program_aids"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Make sure the file is not too heavy. Prefer svg files.",
                null=True,
                upload_to=programs.models.logo_upload_to,
                verbose_name="Logo",
            ),
        ),
    ]
