# Generated by Django 3.2.16 on 2022-11-23 13:00

from django.db import migrations, models
import django.utils.timezone
import programs.models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0010_program_perimeter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ["name"],
                "verbose_name": "Programme d’aides",
                "verbose_name_plural": "Programmes d’aides",
            },
        ),
        migrations.AlterField(
            model_name="program",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Évitez les fichiers trop lourds. Préférez les fichiers SVG.",
                null=True,
                upload_to=programs.models.logo_upload_to,
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Sera affichée dans les SERPs. À garder < 120 caractères.",
                max_length=120,
                verbose_name="Description (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="\n        Le titre qui sera affiché dans les SERPs. Il est recommandé de le garder < 60\n        caractères. Laissez vide pour réutiliser le nom du programme.\n        ",
                max_length=60,
                verbose_name="Titre (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="program",
            name="short_description",
            field=models.CharField(
                help_text="300 caractères max. Résultats de recherche uniquement.",
                max_length=300,
                verbose_name="Brève description",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="slug",
            field=models.SlugField(verbose_name="Fragment d’URL"),
        ),
    ]
