# Generated by Django 3.2.16 on 2022-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0011_auto_20221123_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="is_spotlighted",
            field=models.BooleanField(
                default=False,
                help_text="Si le programme est mis en avant, son logo apparaît sur la page d’accueil",
                verbose_name="Le programme est-il mis en avant ?",
            ),
        ),
    ]
