# Generated by Django 3.2.16 on 2022-12-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_tab"),
        ("programs", "0011_auto_20221123_1400"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramTab",
            fields=[],
            options={
                "verbose_name": "onglet",
                "verbose_name_plural": "onglets",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pages.tab",),
        ),
    ]
