# Generated by Django 3.2.16 on 2023-01-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0012_programtab"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programtab",
            options={
                "verbose_name": "onglet programme",
                "verbose_name_plural": "onglets programme",
            },
        ),
    ]
