# Generated by Django 4.1.5 on 2023-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0013_alter_programtab_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="is_spotlighted",
            field=models.BooleanField(
                default=False,
                help_text="Si le programme est mis en avant, son logo apparaît sur la page d’accueil",
                verbose_name="Le programme est-il mis en avant ?",
            ),
        ),
    ]
