# Generated by Django 2.1 on 2018-08-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0004_aid_backer"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="eligibility",
            field=models.TextField(default="", verbose_name="Eligibility"),
            preserve_default=False,
        ),
    ]
