# Generated by Django 2.1 on 2018-08-15 13:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0007_auto_20180815_1105"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                null=True,
                size=20,
                verbose_name="Keywords",
            ),
        ),
    ]
