# Generated by Django 2.1 on 2018-08-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0015_auto_20180829_1049"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="recurrence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("oneoff", "One off"),
                    ("ongoing", "Ongoing"),
                    ("recurring", "Recurring"),
                ],
                max_length=16,
                verbose_name="Recurrence",
            ),
        ),
    ]
