# Generated by Django 2.1.1 on 2018-09-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0005_remove_perimeter_commune"),
        ("aids", "0016_aid_recurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="perimeter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geofr.Perimeter",
                verbose_name="Perimeter",
            ),
        ),
    ]
