# Generated by Django 2.1.1 on 2018-09-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0017_aid_perimeter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="description",
            field=models.TextField(max_length=500, verbose_name="Description"),
        ),
    ]
