# Generated by Django 2.1.1 on 2018-09-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0019_auto_20180906_1148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aid",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="aid",
            name="thematics",
        ),
    ]
