# Generated by Django 2.1.1 on 2018-09-13 08:07

from django.db import migrations


def remove_survey_values(apps, schema_editor):
    """Merge values in aid destination field.

    The `survey` value is deleted and merged into `service`.

    """

    Aid = apps.get_model("aids", "Aid")

    aids = Aid.objects.all()

    for aid in aids:
        if "survey" in aid.destinations and "service" not in aid.destinations:
            aid.destinations = aid.destinations + ["service"]

        if "survey" in aid.destinations:
            aid.destinations.remove("survey")

        if "other" in aid.destinations:
            aid.destinations.remove("other")

        aid.save()


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0021_auto_20180913_1007"),
    ]

    operations = [
        migrations.RunPython(remove_survey_values, migrations.RunPython.noop),
    ]
