# Generated by Django 2.1.1 on 2018-09-13 08:24

from django.db import migrations


def remove_audiences_values(apps, schema_editor):
    """Remove deleted values in aid audiences field."""

    Aid = apps.get_model('aids', 'Aid')
    aids = Aid.objects.all()

    for aid in aids:
        for field in ('company', 'civil_society', 'association', 'other'):
            if field in aid.targeted_audiences:
                aid.targeted_audiences.remove(field)

        aid.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0022_remove_survey_values'),
    ]

    operations = [
        migrations.RunPython(
            remove_audiences_values, migrations.RunPython.noop),
    ]
