# Generated by Django 2.1.1 on 2018-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0025_auto_20180914_1349"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="application_url",
            field=models.URLField(blank=True, verbose_name="Application url"),
        ),
    ]
