# Generated by Django 2.1.1 on 2018-09-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0029_save_backers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aid",
            name="backer",
        ),
        migrations.AlterField(
            model_name="aid",
            name="backers",
            field=models.ManyToManyField(
                help_text="On a national level if appropriate",
                related_name="aids",
                to="backers.Backer",
                verbose_name="Backers",
            ),
        ),
    ]
