# Generated by Django 2.1.1 on 2018-09-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0033_aid_date_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aid",
            name="application_department",
        ),
        migrations.RemoveField(
            model_name="aid",
            name="application_perimeter",
        ),
        migrations.RemoveField(
            model_name="aid",
            name="application_region",
        ),
        migrations.RemoveField(
            model_name="aid",
            name="is_funding",
        ),
        migrations.RemoveField(
            model_name="aid",
            name="open_to_third_party",
        ),
        migrations.RemoveField(
            model_name="aid",
            name="publication_status",
        ),
    ]
