# Generated by Django 2.1.1 on 2018-10-02 10:04

from uuid import uuid4
from django.db import migrations
from django.utils.text import slugify


def set_slugs(apps, schema_editor):
    Aid = apps.get_model("aids", "Aid")
    aids = Aid.objects.all()
    for aid in aids:
        # Let's prepend random chars to prevent slug duplicates
        full_title = "{}-{}".format(str(uuid4())[:4], aid.name)
        aid.slug = slugify(full_title)[:50]
        aid.save()


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0035_aid_slug"),
    ]

    operations = [
        migrations.RunPython(set_slugs),
    ]
