# Generated by Django 2.1.2 on 2018-11-07 10:51

from django.db import migrations

# from django.db.models import F, Func, Value
from django.contrib.postgres.search import SearchVector


def update_search_vectors(apps, schema_editor):
    Aid = apps.get_model("aids.Aid")
    Aid.objects.update(
        search_vector=SearchVector("name", weight="A", config="french")
        +
        # Commented because there was issue when upgrading Django to 3.2
        # SearchVector(
        #     Func(F('tags'), Value(' '), function='array_to_string'),
        #     weight='A',
        #     config='french') +
        SearchVector("description", weight="B", config="french")
        + SearchVector("eligibility", weight="D", config="french")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0045_aid_search_vector"),
    ]

    operations = [migrations.RunPython(update_search_vectors)]
