# Generated by Django 2.1.2 on 2018-11-07 14:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0046_update_search_vectors"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aid",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="aids_aid_search__5120d8_gin"
            ),
        ),
    ]
