# Generated by Django 2.1.2 on 2018-11-14 11:48

# This migration used the now removed tags app
# and has been edited to remove reference to it.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0047_auto_20181107_1537"),
    ]

    operations = []
