# Generated by Django 2.1.2 on 2018-11-15 15:06

# This migration used the now removed tags app
# and has been edited to remove reference to it.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0048_aid__tags_m2m"),
    ]

    operations = []
