# Generated by Django 2.1.5 on 2019-01-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0053_auto_20181219_1043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=35, verbose_name="Contact phone number"
            ),
        ),
    ]
