# Generated by Django 2.1.5 on 2019-02-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0055_update_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="new_backer",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="New backer"
            ),
        ),
    ]
