# Generated by Django 2.1.5 on 2019-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0055_update_search_vector"),
    ]

    operations = [
        migrations.RenameField(model_name="aid", old_name="url", new_name="origin_url"),
    ]
