# Generated by Django 2.1.5 on 2019-02-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0056_auto_20190213_1548"),
        ("aids", "0056_aid_new_backer"),
    ]

    operations = []
