# Generated by Django 2.1.7 on 2019-02-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0056_aid_new_backer'),
        ('aids', '0056_auto_20190213_1548'),
    ]

    operations = [
    ]
