# Generated by Django 2.1.5 on 2019-02-19 10:13

from django.db import migrations


def set_import_ids_to_none(apps, schema_editor):
    Aid = apps.get_model("aids", "Aid")
    Aid.objects.filter(import_uniqueid="").update(import_uniqueid=None)


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0058_auto_20190219_1112"),
    ]

    operations = [migrations.RunPython(set_import_ids_to_none)]
