# Generated by Django 2.1.5 on 2019-02-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0059_set_import_ids_to_none"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="import_uniqueid",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Unique identifier for imported data",
            ),
        ),
    ]
