# Generated by Django 2.2.1 on 2019-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0063_aid_is_call_for_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="date_published",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="First publication date"
            ),
        ),
    ]
