# Generated by Django 2.2.1 on 2019-06-18 08:26

from django.db import migrations
from django.db.models import F


def set_first_publication_date(apps, schema_migration):
    Aid = apps.get_model("aids.Aid")
    Aid.objects.filter(status="published").update(date_published=F("date_created"))


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0064_aid_date_published"),
    ]

    operations = [migrations.RunPython(set_first_publication_date)]
