# Generated by Django 2.2.5 on 2019-10-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0069_auto_20190916_1104"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aid",
            old_name="amendment_author",
            new_name="amendment_author_name",
        ),
    ]
