# Generated by Django 2.2.5 on 2019-11-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0078_copy_subvention_rates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aid",
            name="subvention_rate",
        ),
    ]
