# Generated by Django 2.2.5 on 2019-11-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0082_aid_subvention_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="subvention_comment",
            field=models.CharField(
                blank=True,
                max_length=256,
                verbose_name="Subvention rate, optional comment",
            ),
        ),
    ]
