# Generated by Django 2.2.7 on 2019-11-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0087_fill_new_contact_field"),
        ("aids", "0086_auto_20191119_1517"),
    ]

    operations = []
