# Generated by Django 2.2.7 on 2019-12-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0093_auto_20191129_1433"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aid",
            old_name="new_backer",
            new_name="financer_suggestion",
        ),
        migrations.AddField(
            model_name="aid",
            name="instructor_suggestion",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Instructor suggestion"
            ),
        ),
    ]
