# Generated by Django 2.2.7 on 2019-12-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0094_auto_20191212_1010"),
        ("aids", "0094_auto_20191209_1121"),
    ]

    operations = []
