# Generated by Django 2.2.8 on 2019-12-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0095_merge_20191213_1551"),
        ("aids", "0096_auto_20191213_1604"),
    ]

    operations = []
