# Generated by Django 2.2.9 on 2020-02-03 13:33

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0099_reformat_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="project_examples",
            field=models.TextField(blank=True, verbose_name="Project examples"),
        ),
    ]
