# Generated by Django 2.2.13 on 2020-06-15 08:55

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0107_update_destinations_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="destinations",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[("supply", "Supply"), ("investment", "Investment")],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Destinations",
            ),
        ),
        migrations.AlterField(
            model_name="aid",
            name="name",
            field=models.CharField(
                help_text="Use an infinitive form to make the aid's purpose clear",
                max_length=180,
                verbose_name="Name",
            ),
        ),
    ]
