# Generated by Django 2.2.16 on 2020-09-21 15:07

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0108_auto_20200615_1055"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aid",
            old_name="targeted_audiances",
            new_name="targeted_audiences",
        ),
    ]
