# Generated by Django 2.2.16 on 2020-09-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0109_aid_in_france_relance"),
        ("aids", "0110_auto_20200921_1715"),
    ]

    operations = []
