# Generated by Django 2.2.16 on 2020-09-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0112_auto_20200922_1602"),
        ("aids", "0111_merge_20200922_1553"),
    ]

    operations = []
