# Generated by Django 2.2.17 on 2020-12-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0116_auto_20201105_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="subvention_comment",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Subvention rate, optional comment",
            ),
        ),
    ]
