# Generated by Django 2.2.16 on 2020-11-23 14:44

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0116_auto_20201105_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='mobilization_steps',
            field=core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('preop', 'Preoperational'), ('op', 'Operational'), ('postop', 'Postoperation')], default=False, max_length=32), null=True, size=None, verbose_name='Mobilization step'),
        ),
    ]
