# Generated by Django 2.2.17 on 2020-11-26 10:55

import hashlib

from django.db import migrations


OPENDATA_URL = 'https://data.laregion.fr/explore/dataset/aides-et-appels-a-projets-de-la-region-occitanie/information/'  # noqa


def update_imported_occitanie_aids_unique_id(apps, schema_editor):
    """Change the way we compute the 'unique_id' of these imported aids."""
    Aid = apps.get_model('aids', 'Aid')
    occitanie_imported_aids = Aid.objects.filter(
        is_imported=True, import_data_url=OPENDATA_URL)
    for occitanie_aid in occitanie_imported_aids:
        url_md5_hash = hashlib.md5(occitanie_aid.origin_url.encode('utf-8')).hexdigest()  # noqa
        occitanie_aid.import_uniqueid = 'OCCITANIE_{}'.format(url_md5_hash)
        occitanie_aid.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0116_auto_20201105_0929'),
    ]

    operations = [
        migrations.RunPython(update_imported_occitanie_aids_unique_id)
    ]
