# Generated by Django 3.1.5 on 2021-02-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0117_auto_20201211_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='aid_typology',
            field=models.CharField(choices=[('generic', 'Generic'), ('local', 'Local'), ('standard', 'Standard')], default='standard', help_text="Generic aid can be used when it' coverage is national. If nothing is selected, then it's a 'standard' aid.", max_length=32, verbose_name='Aid typology'),
        ),
    ]
