# Generated by Django 3.1.6 on 2021-02-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0118_auto_20210216_1000"),
        ("aids", "0119_add_local_caracteristics"),
    ]

    operations = []
