# Generated by Django 3.1.7 on 2021-03-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0120_merge_20210222_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='application_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Application url'),
        ),
        migrations.AlterField(
            model_name='aid',
            name='origin_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Origin URL'),
        ),
        migrations.AlterField(
            model_name='aid',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter, more concise title', max_length=64, null=True, verbose_name='Short title'),
        ),
        migrations.AlterField(
            model_name='aid',
            name='subvention_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subvention rate, optional comment'),
        ),
    ]
