# Generated by Django 3.1.5 on 2021-03-10 14:57

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0121_auto_20210309_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='loan_rate',
            field=core.fields.PercentRangeField(blank=True, help_text='If fixed rate, only fill the max. rate.', null=True, verbose_name='Loan rate, min. and max. (in round %)'),
        ),
        migrations.AddField(
            model_name='aid',
            name='other_financial_aid_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other financial aid, optional comment'),
        ),
        migrations.AddField(
            model_name='aid',
            name='recoverable_advance_rate',
            field=core.fields.PercentRangeField(blank=True, help_text='If fixed rate, only fill the max. rate.', null=True, verbose_name='Recoverable_advance rate, min. and max. (in round %)'),
        ),
    ]
