# Generated by Django 3.1.7 on 2021-04-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210318_1456'),
        ('aids', '0123_aid_import_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='aids', to='projects.Project', verbose_name='Projects'),
        ),
    ]
