# Generated by Django 3.1.8 on 2021-04-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0125_migrate_through_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aid",
            name="financers",
        ),
        migrations.RemoveField(
            model_name="aid",
            name="instructors",
        ),
    ]
