# Generated by Django 3.1.8 on 2021-04-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0014_reupload_medias"),
        ("aids", "0128_auto_20210413_1107"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aidfinancer",
            options={"ordering": ["order", "backer__name"]},
        ),
        migrations.AlterModelOptions(
            name="aidinstructor",
            options={"ordering": ["order", "backer__name"]},
        ),
        migrations.AlterUniqueTogether(
            name="aidfinancer",
            unique_together={("aid", "backer")},
        ),
        migrations.AlterUniqueTogether(
            name="aidinstructor",
            unique_together={("aid", "backer")},
        ),
    ]
