# Generated by Django 3.1.8 on 2021-05-04 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0131_convert_generic_fk_to_boolean"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="generic_aid",
            field=models.ForeignKey(
                blank=True,
                help_text="Generic aid associated to a local aid",
                limit_choices_to={"is_generic": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_aids",
                to="aids.aid",
                verbose_name="Generic aid",
            ),
        ),
    ]
