# Generated by Django 3.2.2 on 2021-05-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0133_aid_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="import_raw_object",
            field=models.JSONField(null=True),
        ),
    ]
