# Generated by Django 3.2.4 on 2021-06-03 15:03

from django.db import migrations


def add_special_status_audience(apps, schema_editor):
    """
    At first, when introducing this new special collectivity
    audience, we want it to be widely applied to any aid
    attached to any collectivity.
    """
    Aid = apps.get_model('aids', 'Aid')
    aids = Aid.objects.filter(targeted_audiences__overlap= \
        ['commune', 'epci', 'department', 'region'])
    for aid in aids:
        aid.targeted_audiences.append('special')
        aid.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0134_aid_import_raw_object'),
    ]

    operations = [
        migrations.RunPython(
            add_special_status_audience,
            migrations.RunPython.noop)
    ]
