# Generated by Django 3.2.4 on 2021-06-10 13:14

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0135_add_special_status_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='loan_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='montant du prêt'),
        ),
        migrations.AddField(
            model_name='aid',
            name='other_financial_aid_comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Autre aide financière, commentaire optionnel'),
        ),
        migrations.AddField(
            model_name='aid',
            name='recoverable_advance_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="montant de l'avance récupérable"),
        ),
        migrations.AlterField(
            model_name='aid',
            name='targeted_audiences',
            field=core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('commune', 'Communes'), ('epci', 'Audience EPCI'), ('department', 'Departments'), ('region', 'Regions'), ('special', 'Special status for outre-mer'), ('association', 'Associations'), ('private_sector', 'Private sector'), ('public_cies', 'Local public companies'), ('public_org', 'Public organization'), ('researcher', 'Research'), ('private_person', 'Individuals'), ('farmer', 'Farmers')], max_length=32), blank=True, null=True, size=None, verbose_name='Targeted audiences'),
        ),
    ]
