# Generated by Django 3.2.4 on 2021-06-16 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aids', '0139_auto_20210616_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Qui peux modifier cette aide ?', related_name='contributor_of_aids', to=settings.AUTH_USER_MODEL, verbose_name='Contributeurs'),
        ),
    ]
