# Generated by Django 3.2.4 on 2021-06-25 14:29

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0140_auto_20210625_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="search_vector_unaccented",
            field=django.contrib.postgres.search.SearchVectorField(
                null=True, verbose_name="Search vector unaccented"
            ),
        ),
    ]
