# Generated by Django 3.2.4 on 2021-08-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0144_alter_aid_targeted_audiences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendment',
            options={'verbose_name': 'Amendement', 'verbose_name_plural': 'Amendements'},
        ),
        migrations.AlterModelOptions(
            name='deletedaid',
            options={'verbose_name': 'Aide supprimée', 'verbose_name_plural': 'Aides supprimées'},
        ),
    ]
