# Generated by Django 3.2.6 on 2021-09-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0146_auto_20210806_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='name_initial',
            field=models.CharField(blank=True, help_text='Comment cette aide s’intitule-t-elle au sein de votre structure ? Exemple : AAP Mob’Biodiv', max_length=180, null=True, verbose_name='Nom initial'),
        ),
    ]
