# Generated by Django 3.2.6 on 2021-09-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0146_auto_20210806_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='initial_name',
            field=models.CharField(blank=True, help_text="Quel était le nom initial de l'aide ?", max_length=180, null=True, verbose_name='Nom initial'),
        ),
    ]
