# Generated by Django 3.2.6 on 2021-09-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210921_1433'),
        ('aids', '0148_alter_aid_aid_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='Projets'),
        ),
    ]
