# Generated by Django 3.2.6 on 2021-09-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0148_alter_aid_aid_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aid',
            name='projects',
        ),
    ]
