# Generated by Django 3.2.6 on 2021-09-21 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20210921_1433'),
        ('aids', '0149_remove_aid_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('aid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aids.aid', verbose_name='Aide')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projet')),
            ],
        ),
    ]
