# Generated by Django 3.2.6 on 2021-09-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210921_1433'),
        ('aids', '0150_aidproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='projects',
            field=models.ManyToManyField(blank=True, through='aids.AidProject', to='projects.Project', verbose_name='Projets'),
        ),
    ]
