# Generated by Django 3.2.12 on 2022-03-24 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0153_alter_aid_targeted_audiences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="date_updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de mise à jour"
            ),
        ),
    ]
