# Generated by Django 3.2.12 on 2022-04-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0158_add_keywords_to_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="european_aid",
            field=models.CharField(
                choices=[
                    ("sectorial", "Sectorielle"),
                    ("organizational", "Structurelle"),
                ],
                max_length=32,
                blank=False,
                default=None,
                help_text="Précisez si l'aide européenne est structurelle ou sectorielle",
                null=True,
                verbose_name="Aide européenne ?",
            ),
        ),
    ]
