# Generated by Django 3.2.12 on 2022-04-29 13:08

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0158_add_keywords_to_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='european_aid',
            field=core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('sectorial', 'Sectorielle'), ('organizational', 'Structurelle')], max_length=32), blank=True, help_text="Précisez si l'aide européenne est structurelle ou sectorielle", null=True, size=None, verbose_name='Aide européenne ?'),
        ),
    ]
