# Generated by Django 3.2.12 on 2022-05-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0159_aid_european_aid"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="import_data_mention",
            field=models.CharField(
                blank=True,
                max_length=900,
                null=True,
                verbose_name="Mention du partenariat avec le propriétaire de la donnée",
            ),
        ),
    ]
