# Generated by Django 3.2.14 on 2022-08-09 12:56

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0161_add_programs_to_search_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="aid_types",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("grant", "Subvention"),
                        ("loan", "Prêt"),
                        ("recoverable_advance", "Avance récupérable"),
                        ("cee", "Certificat d'économie d'énergie (CEE)"),
                        ("technical", "Ingénierie technique"),
                        ("financial", "Ingénierie financière"),
                        ("legal", "Ingénierie Juridique / administrative"),
                        ("other", "Autre aide financière"),
                    ],
                    max_length=32,
                ),
                blank=True,
                help_text="Précisez le ou les types de l'aide.",
                null=True,
                size=None,
                verbose_name="Types d'aide",
            ),
        ),
    ]
