# Generated by Django 3.2.14 on 2022-08-18 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aids", "0162_alter_aid_aid_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidproject",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créateur",
            ),
        ),
    ]
