# Generated by Django 3.2.16 on 2022-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0170_alter_aid_aid_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="has_broken_link",
            field=models.BooleanField(
                default=False, verbose_name="Contient un lien cassé ?"
            ),
        ),
    ]
