# Generated by Django 3.2.16 on 2023-01-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0171_aid_has_broken_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="is_charged",
            field=models.BooleanField(
                default=False,
                help_text="Ne pas cocher pour les aides sous adhésion et ajouter la mention         '*sous adhésion' dans les critères d’éligibilité.",
                verbose_name="Aide Payante",
            ),
        ),
    ]
