# Generated by Django 3.2.16 on 2023-01-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0172_aid_is_charged"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="import_updated",
            field=models.BooleanField(
                default=False,
                help_text="Cette aide est en attente d'une revue des mises à jour         proposées par l'outil d'import",
                verbose_name="En attente de revue des données importées mises à jour",
            ),
        ),
    ]
