# Generated by Django 4.1.5 on 2023-02-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0173_aid_import_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aid",
            options={
                "ordering": ["-id"],
                "verbose_name": "Aide",
                "verbose_name_plural": "Aides",
            },
        ),
        migrations.AlterField(
            model_name="aid",
            name="application_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Candidater à l'aide"
            ),
        ),
        migrations.AlterField(
            model_name="aid",
            name="origin_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Plus d'informations"
            ),
        ),
    ]
