# Generated by Django 4.1.5 on 2023-01-24 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_project_image"),
        ("aids", "0173_aid_import_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidproject",
            name="aid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aids.aid",
                verbose_name="Aide",
            ),
        ),
        migrations.AlterField(
            model_name="aidproject",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="Projet",
            ),
        ),
    ]
