# Generated by Django 4.1.6 on 2023-02-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0173_aid_import_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aid",
            options={
                "ordering": ["-id"],
                "verbose_name": "Aide",
                "verbose_name_plural": "Aides",
            },
        ),
    ]
