# Generated by Django 4.1.5 on 2023-01-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0173_aid_import_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidproject",
            name="amount_obtained",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Montant obtenu"
            ),
        ),
    ]
