# Generated by Django 4.1.5 on 2023-01-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0174_aidproject_amount_obtained"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidproject",
            name="aid_unknown",
            field=models.CharField(
                blank=True,
                help_text="Nom de l'aide inconnue dans notre base de données",
                max_length=600,
                null=True,
                verbose_name="Aide inconnue en base",
            ),
        ),
    ]
