# Generated by Django 4.1.7 on 2023-04-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aids", "0175_aid_ds_id_aid_ds_mapping_aid_ds_schema_exists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="subvention_comment",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Taux de subvention (commentaire optionnel)",
            ),
        ),
    ]
