# Generated by Django 4.1.5 on 2023-01-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_project_final_budget_project_is_imported_and_more"),
        ("aids", "0175_aidproject_aid_unknown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidproject",
            name="aid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aids.aid",
                verbose_name="Aide",
            ),
        ),
        migrations.AlterField(
            model_name="aidproject",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="Projet",
            ),
        ),
    ]
