# Generated by Django 4.1.7 on 2023-04-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aids", "0176_alter_aid_subvention_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="loan_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Montant du prêt maximum"
            ),
        ),
    ]
