# Generated by Django 4.2.3 on 2023-07-11 11:05

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aids", "0180_alter_aid_mobilization_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aid",
            name="aid_types",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("grant", "Subvention"),
                        ("loan", "Prêt"),
                        ("recoverable_advance", "Avance récupérable"),
                        ("cee", "Certificat d'économie d'énergie (CEE)"),
                        ("technical_engineering", "Ingénierie technique"),
                        (
                            "strategic_engineering",
                            "Ingénierie de planification et stratégie",
                        ),
                        (
                            "diagnostique_engineering",
                            "ingénierie d’études et diagnostics",
                        ),
                        ("AMOA_engineering", "AMOA / MOD"),
                        ("MOE_engineering", "MOE / MOE déléguée"),
                        ("financial_engineering", "Ingénierie financière"),
                        ("legal_engineering", "Ingénierie Juridique / administrative"),
                        ("administrative_engineering", "Ingénierie administrative"),
                        (
                            "legal_and_regulatory_engineering",
                            "Ingénierie juridique et réglementaire",
                        ),
                        ("formation_engineering", "formation/montée en compétence"),
                        ("other", "Autre aide financière"),
                    ],
                    max_length=32,
                ),
                blank=True,
                help_text="Précisez le ou les types de l’aide.",
                null=True,
                size=None,
                verbose_name="Types d’aide",
            ),
        ),
    ]
