# Generated by Django 4.2.3 on 2023-07-17 11:35

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aids", "0180_alter_aid_destinations"),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="support_type",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[("direct", "Direct"), ("indirect", "Indirect")],
                    max_length=32,
                ),
                blank=True,
                help_text="Précisez le type d'appui de l’aide:         direct (en nature, prestation directe en temps / ETP)         ou indirect (via un financement permettant de financer une prestation d’ingénierie)",
                null=True,
                size=None,
                verbose_name="Type d’appui",
            ),
        ),
        migrations.AlterField(
            model_name="aid",
            name="aid_types",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("grant", "Subvention"),
                        ("loan", "Prêt"),
                        ("recoverable_advance", "Avance récupérable"),
                        ("cee", "Certificat d'économie d'énergie (CEE)"),
                        ("technical_engineering", "Ingénierie technique"),
                        (
                            "strategic_engineering",
                            "Ingénierie de planification et stratégie",
                        ),
                        (
                            "diagnostic_engineering",
                            "Ingénierie d’étude et diagnostic",
                        ),
                        (
                            "animation_engineering",
                            "Ingénierie d’animation et mise en réseau",
                        ),
                        (
                            "AMOA_engineering",
                            "Assistance à maîtrise d’ouvrage / maîtrise d’ouvrage déléguée",
                        ),
                        (
                            "MOE_engineering",
                            "Maîtrise d’oeuvre / Maîtrise d’oeuvre déléguée",
                        ),
                        ("financial_engineering", "Ingénierie financière"),
                        ("legal_engineering", "Ingénierie Juridique / administrative"),
                        ("administrative_engineering", "Ingénierie administrative"),
                        (
                            "legal_and_regulatory_engineering",
                            "Ingénierie juridique et réglementaire",
                        ),
                        ("formation_engineering", "Formation / montée en compétence"),
                        ("other", "Autre aide financière"),
                    ],
                    max_length=32,
                ),
                blank=True,
                help_text="Précisez le ou les types de l’aide.",
                null=True,
                size=None,
                verbose_name="Types d’aide",
            ),
        ),
    ]
