# Generated by Django 3.1.7 on 2021-03-22 18:16

import core.fields
from django.db import migrations, models
import django.utils.timezone
import django_xworkflows.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Let it empty so it will be autopopulated.', verbose_name='Slug')),
                ('short_text', models.TextField(blank=True, help_text='A short, concise introduction', max_length=256, null=True, verbose_name='Short text')),
                ('text', models.TextField(verbose_name='Full text of the post')),
                ('categorie', core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('webinar', 'Webinar'), ('categorie2', 'Categorie 2'), ('categorie3', 'Categorie 3')], max_length=32), blank=True, null=True, size=None, verbose_name='categorie')),
                ('status', django_xworkflows.models.StateField(max_length=16, verbose_name='Status', workflow=django_xworkflows.models._SerializedWorkflow(initial_state='draft', name='PostWorkflow', states=['draft', 'reviewable', 'published', 'deleted']))),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
    ]
