# Generated by Django 3.1.7 on 2021-03-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='blogpostcategory',
            options={'verbose_name': 'Blog Post Category', 'verbose_name_plural': 'Blog Post Categories'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='Let it empty so it will be autopopulated.', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogpostcategory',
            name='slug',
            field=models.SlugField(help_text='Let it empty so it will be autopopulated.', unique=True, verbose_name='Slug'),
        ),
    ]
