# Generated by Django 3.2.2 on 2021-05-19 06:15

from django.db import migrations, models
import django.utils.timezone
import django_xworkflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Let it empty so it will be autopopulated.', verbose_name='Slug')),
                ('short_text', models.TextField(blank=True, help_text='A short, concise introduction', max_length=256, null=True, verbose_name='Short text')),
                ('button_link', models.URLField(verbose_name='Button link')),
                ('button_title', models.CharField(db_index=True, max_length=120, verbose_name='Button title')),
                ('querystring', models.TextField(blank=True, verbose_name='Querystring')),
                ('status', django_xworkflows.models.StateField(max_length=16, verbose_name='Status', workflow=django_xworkflows.models._SerializedWorkflow(initial_state='draft', name='PromotionPostWorkflow', states=['draft', 'reviewable', 'published', 'deleted']))),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Promotion post',
                'verbose_name_plural': 'Promotion posts',
            },
            bases=(django_xworkflows.models.BaseWorkflowEnabled, models.Model),
        ),
    ]
