# Generated by Django 3.2.4 on 2021-07-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cleanup_fields_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategory',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='promotionpost',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
    ]
