# Generated by Django 3.2.16 on 2022-11-18 16:09

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionpost",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Évitez les fichiers trop lourds. Préférez les fichiers svg.",
                null=True,
                upload_to=blog.models.promotion_img_upload_to,
                verbose_name="Illustration",
            ),
        ),
        migrations.AddField(
            model_name="promotionpost",
            name="image_alt_text",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="texte alternatif pour l'image",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpost",
            name="button_title",
            field=models.CharField(max_length=120, verbose_name="Titre du bouton"),
        ),
        migrations.AlterField(
            model_name="promotionpost",
            name="short_text",
            field=models.TextField(
                blank=True,
                help_text="Introduction concise (inférieure à 256 caractères).",
                null=True,
                verbose_name="Texte d'introduction",
            ),
        ),
    ]
