# Generated by Django 4.1.5 on 2023-03-27 08:32

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_textfield_image_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionpost",
            name="external_link",
            field=models.BooleanField(default=False, verbose_name="Lien externe ?"),
        ),
        migrations.AddField(
            model_name="promotionpost",
            name="targeted_audiences",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("commune", "Communes"),
                        ("epci", "Intercommunalités / Pays"),
                        ("department", "Départements"),
                        ("region", "Régions"),
                        ("special", "Collectivités d'outre-mer à statuts particuliers"),
                        ("association", "Associations"),
                        ("private_person", "Particuliers"),
                        ("farmer", "Agriculteurs"),
                        ("private_sector", "Entreprises privées"),
                        (
                            "public_cies",
                            "Entreprises publiques locales (Sem, Spl, SemOp)",
                        ),
                        (
                            "public_org",
                            "Établissements publics (écoles, bibliothèques…) / Services de l'État",
                        ),
                        ("researcher", "Recherche"),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Bénéficiaires",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="La description qui sera affiché dans les SERPs. Il est recommandé de le garder < 120 caractères. ",
                max_length=256,
                verbose_name="Description (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Le titre qui sera affiché dans les SERPs. Il est recommandé de le garder < 60 caractères. Laissez vide pour réutiliser le titre de l'article.",
                max_length=180,
                verbose_name="Titre (balise meta)",
            ),
        ),
    ]
