# flake8: noqa
# Generated by Django 4.2.1 on 2023-06-02 13:51

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0015_backer_perimeter"),
        ("blog", "0007_promotionpost_external_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="blog.blogpostcategory",
                verbose_name="Catégorie de l’article de blog",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Évitez les fichiers trop lourds. Préférez les fichiers SVG.",
                null=True,
                upload_to=blog.models.logo_upload_to,
                verbose_name="Illustration",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Le titre qui sera affiché dans les SERPs. Il est recommandé de le garder < 60 caractères. Laissez vide pour réutiliser le titre de l’article.",
                max_length=180,
                verbose_name="Titre (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="short_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Introduction concise (inférieure à 256 caractères).",
                max_length=256,
                verbose_name="Texte d’introduction",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Laisser vide pour autoremplir.",
                verbose_name="Fragment d’URL",
            ),
        ),
        migrations.AlterField(
            model_name="blogpostcategory",
            name="slug",
            field=models.SlugField(
                help_text="Laisser vide pour autoremplir.",
                unique=True,
                verbose_name="Fragment d’URL",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpost",
            name="backers",
            field=models.ManyToManyField(
                blank=True,
                related_name="promotionsPost",
                to="backers.backer",
                verbose_name="Porteurs d’aides",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpost",
            name="image_alt_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="texte alternatif pour l’image",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="promotionpost",
            name="short_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Introduction concise (inférieure à 256 caractères).",
                verbose_name="Texte d’introduction",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="promotionpost",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Laisser vide pour autoremplir.",
                verbose_name="Fragment d’URL",
            ),
        ),
    ]
