# Generated by Django 4.2.4 on 2023-08-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keywords", "0002_synonymlist_model"),
        ("blog", "0008_alter_blogpost_category_alter_blogpost_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionpost",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                related_name="promotionsPost",
                to="keywords.synonymlist",
                verbose_name="Listes de synonymes",
            ),
        ),
    ]
