# Generated by Django 3.1.7 on 2021-02-23 14:28

from django.db import migrations
from django.db.migrations import RunPython
from core.utils import reupload_files


class Migration(migrations.Migration):

    dependencies = [
        ("exporting", "0001_initial"),
    ]

    operations = [
        RunPython(
            reupload_files("exporting.DataExport", "exported_file"), RunPython.noop
        )
    ]
