# Generated by Django 4.1.7 on 2023-03-24 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exporting", "0002_reupload_files"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dataexport",
            options={
                "verbose_name": "Export de données",
                "verbose_name_plural": "Exports de données",
            },
        ),
        migrations.AlterField(
            model_name="dataexport",
            name="author",
            field=models.ForeignKey(
                help_text="La personne qui a déclenché l’export",
                limit_choices_to={"is_superuser": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="dataexport",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="dataexport",
            name="exported_file",
            field=models.FileField(
                upload_to="data-export", verbose_name="fichier exporté"
            ),
        ),
    ]
