# Generated by Django 2.2.13 on 2020-07-06 07:50

from django.db import migrations, models
import search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_auto_20200217_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main displayed title.', max_length=180, verbose_name='Title')),
                ('meta_title', models.CharField(blank=True, default='', help_text='This will be displayed in SERPs. Keep it under 60 characters. Leave empty and we will reuse the page title.', max_length=180, verbose_name='Meta title')),
                ('slug', models.SlugField(help_text="This part is used in the url. DON't change this for existing pages.", verbose_name='Slug')),
                ('meta_description', models.TextField(blank=True, default='', help_text='This will be displayed in SERPs. Keep it under 120 characters.', max_length=256, verbose_name='Meta description')),
                ('content', models.TextField(help_text='Full description of the page. Will be displayed above results.', verbose_name='Page content')),
                ('search_querystring', models.TextField(help_text='The search paramaters url', verbose_name='Querystring')),
                ('color_1', models.CharField(blank=True, help_text='Main background color', max_length=10, verbose_name='Color 1')),
                ('color_2', models.CharField(blank=True, help_text='Search form background color', max_length=10, verbose_name='Color 2')),
                ('color_3', models.CharField(blank=True, help_text='Buttons and title borders color', max_length=10, verbose_name='Color 3')),
                ('logo', models.FileField(blank=True, help_text='Make sure the file is not too heavy. Prefer svg files.', null=True, upload_to=search.models.logo_upload_to, verbose_name='Logo image')),
                ('color_4', models.CharField(blank=True, help_text='Link colors', max_length=10, verbose_name='Color 4')),
                ('logo_link', models.URLField(blank=True, help_text="The url for the partner's logo link", null=True, verbose_name='Logo link')),
                ('color_5', models.CharField(blank=True, help_text='Footer background color', max_length=10, verbose_name='Color 5')),
                ('available_categories', models.ManyToManyField(blank=True, related_name='search_pages', to='categories.Category', verbose_name='Categories')),
                ('more_content', models.TextField(blank=True, help_text='Hidden content, revealed with a `See more` button', verbose_name='Additional page content')),
            ],
            options={
                'verbose_name': 'Search page',
                'verbose_name_plural': 'Search pages',
            },
        ),
    ]
