# Generated by Django 2.2.13 on 2020-06-08 08:11

from django.db import migrations, models
import search.models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_auto_20200608_0955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchpage",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Make sure the file is not too heavy. Prefer svg files.",
                null=True,
                upload_to=search.models.logo_upload_to,
                verbose_name="Logo image",
            ),
        ),
    ]
