# Generated by Django 2.2.13 on 2020-07-23 14:30

from django.db import migrations, models
import search.models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0010_auto_20200709_1150"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchpage",
            name="meta_image",
            field=models.FileField(
                blank=True,
                help_text="Make sure the file is at least 1024px long.",
                null=True,
                upload_to=search.models.logo_upload_to,
                verbose_name="Meta image",
            ),
        ),
    ]
