# Generated by Django 2.2.13 on 2020-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0012_auto_20200907_0933"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchpage",
            name="show_mobilization_steps_field",
            field=models.BooleanField(
                default=False, verbose_name="Show mobilization steps filter?"
            ),
        ),
    ]
