# Generated by Django 2.2.13 on 2020-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0013_searchpage_show_mobilization_steps_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchpage",
            old_name="show_mobilization_steps_field",
            new_name="show_mobilization_step_field",
        ),
    ]
