# Generated by Django 2.2.16 on 2020-09-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0014_auto_20200910_1041"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchpage",
            old_name="show_audiance_field",
            new_name="show_audience_field",
        ),
    ]
