# Generated by Django 2.2.16 on 2020-09-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0015_auto_20200921_1219"),
        ("search", "0015_auto_20200921_1715"),
    ]

    operations = []
