# Generated by Django 2.2.16 on 2020-10-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofr', '0028_auto_20200616_1117'),
        ('search', '0018_add_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpage',
            name='available_perimeter',
            field=models.ManyToManyField(blank=True, related_name='search_pages', to='geofr.Perimeter', verbose_name='Perimeter'),
        ),
        migrations.AlterField(
            model_name='searchpage',
            name='short_title',
            field=models.CharField(blank=True, default='', help_text='A shorter, more concise title.', max_length=180, verbose_name='Short title'),
        ),
    ]
