# Generated by Django 2.2.17 on 2020-12-10 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0019_auto_20201028_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchpage",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date created"
            ),
        ),
    ]
