# Generated by Django 2.2.16 on 2020-10-30 17:25

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_auto_20201030_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchpage',
            name='available_perimeter',
        ),
        migrations.AddField(
            model_name='searchpage',
            name='available_perimeter',
            field=core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('Collectivities', (('commune', 'Communes'), ('epci', 'Audience EPCI'), ('department', 'Departments'), ('region', 'Regions'))), ('Other audiences', (('association', 'Associations'), ('private_person', 'Individuals'), ('farmer', 'Farmers'), ('private_sector', 'Private sector'), ('public_cies', 'Local public companies'), ('public_org', 'Public organizations / State services'), ('researcher', 'Research')))], max_length=32), blank=True, null=True, size=None, verbose_name='Perimeter'),
        ),
    ]
