# Generated by Django 2.2.17 on 2020-12-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0020_searchpage_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchpage",
            name="show_aid_type_field",
            field=models.BooleanField(
                default=False, verbose_name="Show aid type filter?"
            ),
        ),
    ]
