# Generated by Django 2.2.16 on 2020-10-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofr', '0028_auto_20200616_1117'),
        ('search', '0020_auto_20201030_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchpage',
            name='available_perimeter',
        ),
        migrations.AddField(
            model_name='searchpage',
            name='available_perimeter',
            field=models.ManyToManyField(blank=True, related_name='search_pages', to='geofr.Perimeter', verbose_name='Perimeter'),
        ),
    ]
