# Generated by Django 3.1.7 on 2021-02-23 14:29

from django.db import migrations
from django.db.migrations import RunPython
from core.utils import reupload_files


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0023_searchpage_excluded_aids"),
    ]

    operations = [
        RunPython(reupload_files("search.SearchPage", "logo"), RunPython.noop),
        RunPython(reupload_files("search.SearchPage", "meta_image"), RunPython.noop),
    ]
