# Generated by Django 3.1.7 on 2021-03-17 12:02

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_reupload_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpage',
            name='available_audiences',
            field=core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('Collectivities', (('commune', 'Communes'), ('epci', 'Audience EPCI'), ('department', 'Departments'), ('region', 'Regions'))), ('Other audiences', (('association', 'Associations'), ('private_sector', 'Private sector'), ('public_cies', 'Local public companies'), ('public_org', 'Public organizations / State services'), ('researcher', 'Research'), ('farmer', 'Farmers'), ('private_person', 'Individuals')))], max_length=32), blank=True, null=True, size=None, verbose_name='Targeted audiences'),
        ),
    ]
