# Generated by Django 3.2.3 on 2021-06-07 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0026_searchpage_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_pages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.RenameField(
            model_name='searchpage',
            old_name='administrators',
            new_name='contributors'
        )
    ]
