# Generated by Django 3.2.4 on 2021-06-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_minisitepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpage',
            name='show_backers_field',
            field=models.BooleanField(default=False, verbose_name='Montrer le champ « porteur » ?'),
        ),
    ]
