# Generated by Django 3.2.3 on 2021-06-07 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0027_searchpage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpage',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributor_of_search_pages', to=settings.AUTH_USER_MODEL, verbose_name='Contributors'),
        ),
    ]
