# Generated by Django 3.2.3 on 2021-06-07 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_alter_page_minisite'),
        ('search', '0027_auto_20210607_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinisitePage',
            fields=[
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.page',),
        ),
        migrations.AlterField(
            model_name='searchpage',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributor_of_search_pages', to=settings.AUTH_USER_MODEL, verbose_name='Contributors'),
        ),
    ]
