# Generated by Django 3.2.4 on 2021-06-14 08:08

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0030_searchpage_administrators_to_administrator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchpage",
            name="available_audiences",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "Collectivities",
                            (
                                ("commune", "Communes"),
                                ("epci", "Audience EPCI"),
                                ("department", "Departments"),
                                ("region", "Regions"),
                                ("special", "Special status for outre-mer"),
                            ),
                        ),
                        (
                            "Other audiences",
                            (
                                ("association", "Associations"),
                                ("private_person", "Individuals"),
                                ("farmer", "Farmers"),
                                ("private_sector", "Private sector"),
                                ("public_cies", "Local public companies"),
                                ("public_org", "Public organizations / State services"),
                                ("researcher", "Research"),
                            ),
                        ),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Targeted audiences",
            ),
        ),
    ]
