# Generated by Django 3.2.4 on 2021-06-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0032_cleanup_choices_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpage',
            name='tab_title',
            field=models.CharField(blank=True, default='Accueil', max_length=180, verbose_name="Titre de l'onglet principal"),
        ),
    ]
