# Generated by Django 3.2.4 on 2021-06-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0032_cleanup_choices_translations"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchPageLite",
            fields=[],
            options={
                "verbose_name": "page personnalisée",
                "verbose_name_plural": "pages personnalisées",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("search.searchpage",),
        ),
    ]
