# Generated by Django 3.2.6 on 2021-11-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0035_add_tab_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchpage",
            name="show_text_field",
            field=models.BooleanField(
                default=False, verbose_name="Montrer le champ « recherche textuelle » ?"
            ),
        ),
    ]
