# Generated by Django 3.2.12 on 2022-03-01 10:04

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0036_searchpage_show_text_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchpage",
            name="available_audiences",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "Collectivités",
                            (
                                ("commune", "Communes"),
                                ("epci", "Intercommunalités / Pays"),
                                ("department", "Départements"),
                                ("region", "Régions"),
                                (
                                    "special",
                                    "Collectivités d'outre-mer à statuts particuliers",
                                ),
                            ),
                        ),
                        (
                            "Autres bénéficiaires",
                            (
                                ("association", "Associations"),
                                ("private_person", "Particuliers"),
                                ("farmer", "Agriculteurs"),
                                ("private_sector", "Entreprises privées"),
                                (
                                    "public_cies",
                                    "Entreprises publiques locales (Sem, Spl, SemOp)",
                                ),
                                (
                                    "public_org",
                                    "Établissements publics (écoles, bibliothèques…) / Services de l'État",
                                ),
                                ("researcher", "Recherche"),
                            ),
                        ),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Targeted audiences",
            ),
        ),
    ]
