# Generated by Django 4.2.1 on 2023-05-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0039_searchpage_contact_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchpage",
            name="subdomain_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Afficher depuis un sous-domaine ?"
            ),
        ),
    ]
