# Generated by Django 4.2.1 on 2023-06-05 14:06

import core.fields
from django.db import migrations, models
import django.utils.timezone
import search.models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0005_alter_theme_short_description"),
        ("aids", "0178_alter_aid_application_url_alter_aid_origin_url"),
        ("search", "0040_searchpage_subdomain_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchpage",
            name="available_audiences",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "Collectivités",
                            (
                                ("commune", "Communes"),
                                ("epci", "Intercommunalités / Pays"),
                                ("department", "Départements"),
                                ("region", "Régions"),
                                (
                                    "special",
                                    "Collectivités d'outre-mer à statuts particuliers",
                                ),
                            ),
                        ),
                        (
                            "Autres bénéficiaires",
                            (
                                ("association", "Associations"),
                                ("private_person", "Particuliers"),
                                ("farmer", "Agriculteurs"),
                                ("private_sector", "Entreprises privées"),
                                (
                                    "public_cies",
                                    "Entreprises publiques locales (Sem, Spl, SemOp)",
                                ),
                                (
                                    "public_org",
                                    "Établissements publics (écoles, bibliothèques…) / Services de l'État",
                                ),
                                ("researcher", "Recherche"),
                            ),
                        ),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Bénéficiaires de l'aide",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="available_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="search_pages",
                to="categories.category",
                verbose_name="Sous-thématiques",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="color_1",
            field=models.CharField(
                blank=True,
                help_text="Couleur du fond principal",
                max_length=10,
                verbose_name="Couleur 1",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="color_2",
            field=models.CharField(
                blank=True,
                help_text="Couleur du formulaire de recherche",
                max_length=10,
                verbose_name="Couleur 2",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="color_3",
            field=models.CharField(
                blank=True,
                help_text="Couleur des boutons et bordures de titres",
                max_length=10,
                verbose_name="Couleur 3",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="color_4",
            field=models.CharField(
                blank=True,
                help_text="Couleur des liens",
                max_length=10,
                verbose_name="Couleur 4",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="color_5",
            field=models.CharField(
                blank=True,
                help_text="Couleur de fond du pied de page",
                max_length=10,
                verbose_name="Couleur 5",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="content",
            field=models.TextField(
                help_text="Description complète de la page. Sera affichée au dessus des résultats.",
                verbose_name="Contenu de la page",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="excluded_aids",
            field=models.ManyToManyField(
                blank=True,
                related_name="excluded_from_search_pages",
                to="aids.aid",
                verbose_name="Aides à exclure",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="highlighted_aids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Il est possible de mettre jusqu'à 9 aides en avant.              Les aides mises en avant s'affichent en haut des résultats du portail,              et n’ont pas de mise en forme particulière.",
                related_name="highlighted_in_search_pages",
                to="aids.aid",
                verbose_name="Aides à mettre en avant",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Évitez les fichiers trop lourds. Préférez les fichiers svg.",
                null=True,
                upload_to=search.models.logo_upload_to,
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="logo_link",
            field=models.URLField(
                blank=True,
                help_text="L'url vers laquelle renvoie un clic sur le logo partenaire",
                null=True,
                verbose_name="Lien du logo",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Sera affichée dans les SERPs. À garder < 120 caractères.",
                max_length=256,
                verbose_name="Meta description",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="meta_image",
            field=models.FileField(
                blank=True,
                help_text="Vérifiez que l'image a une largeur minimale de 1024px",
                null=True,
                upload_to=search.models.meta_upload_to,
                verbose_name="Meta image",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Le titre qui sera affiché dans les SERPs.            Il est recommandé de le garder <             60 caractères. Laissez vide pour réutiliser le titre de la page.",
                max_length=180,
                verbose_name="Meta titre",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="more_content",
            field=models.TextField(
                blank=True,
                help_text="Contenu révélé au clic sur le bouton «\xa0Voir plus\xa0».",
                verbose_name="Contenu additionnel",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="search_querystring",
            field=models.TextField(
                help_text="Les paramètres de recherche en format url",
                verbose_name="Querystring",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="short_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Un titre plus concis, pour affichage spécifique",
                max_length=180,
                verbose_name="Titre court",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="slug",
            field=models.SlugField(
                help_text="Cette partie est utilisée dans l'url.              NE PAS CHANGER pour une page.             DOIT être en minuscule pour les sites partenaires.",
                verbose_name="Fragment d’URL",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="title",
            field=models.CharField(
                help_text="Le titre principal.", max_length=180, verbose_name="Titre"
            ),
        ),
    ]
