# Generated by Django 4.2.3 on 2023-08-04 11:11

import core.fields
from django.db import migrations, models
import search.models


class Migration(migrations.Migration):

    dependencies = [
        ("aids", "0179_aid_contact_info_updated_alter_aid_aid_types_and_more"),
        ("search", "0041_alter_searchpage_available_audiences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchpage",
            name="available_audiences",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "Collectivités",
                            (
                                ("commune", "Communes"),
                                ("epci", "Intercommunalités / Pays"),
                                ("department", "Départements"),
                                ("region", "Régions"),
                                (
                                    "special",
                                    "Collectivités d'outre-mer à statuts particuliers",
                                ),
                            ),
                        ),
                        (
                            "Autres bénéficiaires",
                            (
                                ("association", "Associations"),
                                ("private_person", "Particuliers"),
                                ("farmer", "Agriculteurs"),
                                ("private_sector", "Entreprises privées"),
                                (
                                    "public_cies",
                                    "Entreprises publiques locales (Sem, Spl, SemOp)",
                                ),
                                (
                                    "public_org",
                                    "Établissements publics (écoles, bibliothèques…) / Services de l'État",
                                ),
                                ("researcher", "Recherche"),
                            ),
                        ),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Bénéficiaires de l’aide",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="contact_link",
            field=models.CharField(
                default="https://aides-territoires.beta.gouv.fr/contact/",
                help_text="URL ou adresse email qui sera utilisé\n        pour le lien «\xa0contact\xa0» dans le footer.",
                max_length=300,
                verbose_name="URL du lien contact",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="highlighted_aids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Il est possible de mettre jusqu’à 9 aides en avant.              Les aides mises en avant s’affichent en haut des résultats du portail,              et n’ont pas de mise en forme particulière.",
                related_name="highlighted_in_search_pages",
                to="aids.aid",
                verbose_name="Aides à mettre en avant",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="logo_link",
            field=models.URLField(
                blank=True,
                help_text="L’URL vers laquelle renvoie un clic sur le logo partenaire",
                null=True,
                verbose_name="Lien du logo",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Sera affichée dans les SERPs. À garder < 120 caractères.",
                max_length=256,
                verbose_name="Description (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="meta_image",
            field=models.FileField(
                blank=True,
                help_text="Vérifiez que l’image a une largeur minimale de 1024px",
                null=True,
                upload_to=search.models.meta_upload_to,
                verbose_name="Image (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Le titre qui sera affiché dans les SERPs.            Il est recommandé de le garder <             60 caractères. Laissez vide pour réutiliser le titre de la page.",
                max_length=180,
                verbose_name="Titre (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="search_querystring",
            field=models.TextField(
                help_text="Les paramètres de recherche en format URL",
                verbose_name="Querystring",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="show_aid_type_field",
            field=models.BooleanField(
                default=False, verbose_name="Montrer le champ « nature de l’aide » ?"
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="slug",
            field=models.SlugField(
                help_text="Cette partie est utilisée dans l’URL.\n             NE PAS CHANGER pour une page.\n            DOIT être en minuscule pour les sites partenaires.\n            Longueur max\xa0:33 caractères, mais si possible ne pas dépasser 23.",
                max_length=33,
                verbose_name="Fragment d’URL",
            ),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="tab_title",
            field=models.CharField(
                blank=True,
                default="Accueil",
                max_length=180,
                verbose_name="Titre de l’onglet principal",
            ),
        ),
    ]
