# Generated by Django 2.2.1 on 2019-05-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmark",
            old_name="user",
            new_name="owner",
        ),
    ]
