# Generated by Django 2.2.1 on 2019-06-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0002_auto_20190528_1119"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="title",
            field=models.CharField(default="", max_length=250, verbose_name="Title"),
            preserve_default=False,
        ),
    ]
