# Generated by Django 2.2.5 on 2019-10-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0005_bookmark_latest_alert_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="alert_frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly")],
                default="daily",
                max_length=32,
            ),
        ),
    ]
