# Generated by Django 3.2.16 on 2022-11-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0009_alter_bookmark_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bookmark",
        ),
    ]
