# Generated by Django 3.1.7 on 2021-02-23 14:29

from django.db import migrations
from django.db.migrations import RunPython
from core.utils import reupload_files


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        RunPython(reupload_files("upload.UploadImage", "image"), RunPython.noop)
    ]
