# Generated by Django 3.2.5 on 2021-07-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_reupload_files"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadimage",
            options={"verbose_name": "image", "verbose_name_plural": "images"},
        ),
    ]
