---
- name: Run application building steps
  become: yes
  become_user: "{{ user_name }}"
  block:

    - name: Build
      debug:
        msg: "Starting building tasks"
        verbosity: 3

    - name: Pull / clone main project repo
      when: project_env == "production"
      git:
        repo: "{{ project_repo }}"
        dest: "{{ project_root }}"
        version: "{{ project_version }}"
        accept_hostkey: yes

    - name: Copy private production settings to the remote
      when: project_env == "production"
      copy:
        src: ../../../src/{{ env_file }}
        dest: "{{ django_root }}/{{ env_target }}"

    - name: Install python packages for production
      when: project_env == "production"
      shell: |
        . {{ activate_bin }} && {{ pipenv_bin }} sync
      args:
        chdir: "{{ django_root }}"

    - name: Install python packages for dev
      when: project_env == "local"
      shell: |
        . {{ activate_bin }} && {{ pipenv_bin }} sync --dev
      args:
        chdir: "{{ django_root }}"

    - name: Install js packages assets
      shell: npm ci
      args:
        chdir: "{{ django_root }}"

    - name: Run Django database migrations
      django_manage:
        command: migrate
        app_path: "{{ django_root }}"
        virtualenv: "{{ venv_dir }}"
        settings: "{{ django_settings }}"

    - name: Collect static
      django_manage:
        command: collectstatic
        app_path: "{{ django_root }}"
        virtualenv: "{{ venv_dir }}"
        settings: "{{ django_settings }}"

    - name: Compile locale files
      django_manage:
        command: compilemessages
        app_path: "{{ django_root }}"
        virtualenv: "{{ venv_dir }}"
        settings: "{{ django_settings }}"

    - name: Compress assets
      when: project_env == "production"
      django_manage:
        command: compress
        app_path: "{{ django_root }}"
        virtualenv: "{{ venv_dir }}"
        settings: "{{ django_settings }}"
