---
- name: Use Bash as the shell
  cronvar:
    name: SHELL
    value: /bin/bash
    user: "{{ user_name }}"
  tags: cronjobs

- name: Disable emails
  cronvar:
    name: MAILTO
    value: "''"
    user: "{{ user_name }}"
  tags: cronjobs

- name: Ensure new aid email alert cronjob is setup
  cron:
    name: Send alert when new aids are created
    state: absent
    user: "{{ user_name }}"
    minute: "42"
    hour: "7"
    job: "cd {{ django_root }} && source {{ activate_bin }} && {{ pipenv_bin }} run ./manage.py new_aids_alert --settings={{ django_settings }} &>> {{ cron_log_root }}"
  tags: cronjobs

- name: Ensure the aids waiting for review email alert cronjob is setup
  cron:
    name: Send alert when aids are waiting for review
    state: absent
    user: "{{ user_name }}"
    minute: "44"
    hour: "7"
    job: "cd {{ django_root }} && source {{ activate_bin }} && {{ pipenv_bin }} run ./manage.py reviewable_aids_alert --settings={{ django_settings }} &>> {{ cron_log_root }}"
  tags: cronjobs

- name: Install the daily ademe data import task
  cron:
    name: Import data from the ademe's feed
    user: "{{ user_name }}"
    minute: "42"
    hour: "2"
    job: "cd {{ django_root }} && source {{ activate_bin }} && {{ pipenv_bin }} run ./manage.py import_ademe --settings={{ django_settings }} &>> {{ cron_log_root }}"
  tags: cronjobs

- name: Install the alert sending task
  cron:
    name: Send alert emails
    user: "{{ user_name }}"
    minute: "42"
    hour: "3"
    job: "cd {{ django_root }} && source {{ activate_bin }} && {{ pipenv_bin }} run ./manage.py send_alerts --settings={{ django_settings }} &>> {{ cron_log_root }}"
  tags: cronjobs

- name: Install the task for exporting contacts to SendinBlue
  cron:
    name: Export contacts
    user: "{{ user_name }}"
    minute: "42"
    hour: "5"
    job: "cd {{ django_root }} && source {{ activate_bin }} && {{ pipenv_bin }} run ./manage.py export_contacts --settings={{ django_settings }} &>> {{ cron_log_root }}"
  tags: cronjobs
