---
- name: Ensure the "new aids email alert" cronjob is setup
  cron:
    name: "new aids email alert"
    user: "{{ user_name }}"
    minute: "42"
    hour: "7"
    job: "cd {{ django_root }} && {{ pipenv_bin }} run manage.py new_aids_alert --settings={{ django_settings }}"
