---
- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ django_root }}"
    virtualenv: "{{ venv_dir }}"
    settings: "{{ django_settings }}"
  notify: Restart django
