---
- name: Create database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: aides
    password: aides

- name: Create postgres Database
  become: yes
  become_user: postgres
  postgresql_db:
    name: aides
    owner: aides

- name: Install required Postgres extensions
  become: yes
  become_user: postgres
  postgresql_ext:
    name: "{{ item }}"
    db: aides
  with_items:
    - btree_gin
    - pg_trgm
