---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install apt https driver
  apt:
    name: apt-transport-https
    state: present

- name: Install nodesource apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add nodesource apt repository to install NodeJs
  apt_repository:
    repo: deb https://deb.nodesource.com/node_8.x stretch main
    state: present
    filename: nodesource

- name: Update apt cache again
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - gettext
    - postgresql
    - libpq-dev
    - python-psycopg2
    - python-virtualenv
    - git
    - nginx
    - supervisor
    - nodejs
    - certbot
    - python3
    - python3-dev
    - python3-pip
    - python3-virtualenv

- name: Install sass
  npm:
    name: sass
    global: yes
