---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install apt https driver
  apt:
    name: apt-transport-https
    state: present

- name: Upgrade all packages
  apt:
    upgrade: safe
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - gettext
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
      - python-virtualenv
      - build-essential
      - git
      - nginx
      - supervisor
      - certbot
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - python3-venv
      - gnupg
      - redis-server

- name: Install nodesource apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add nodesource apt repository to install NodeJs
  apt_repository:
    repo: deb https://deb.nodesource.com/node_12.x buster main
    state: present
    filename: nodesource

- name: Install nodejs
  apt:
    name: nodejs
    update_cache: yes
    state: latest

- name: Removes sass js version
  npm:
    name: sass
    global: yes
    state: absent

- name: Download the sass binary
  get_url:
    url: https://github.com/sass/dart-sass/releases/download/1.24.2/dart-sass-1.24.2-linux-x64.tar.gz
    dest: /tmp/sass.tgz

- name: Extracts sass binary
  unarchive:
    src: /tmp/sass.tgz
    dest: /opt/
    remote_src: yes

- name: Create symlink to sass binary
  file:
    src: /opt/dart-sass/sass
    dest: /usr/local/bin/sass
    state: link
