---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Pin package priorities
  template:
    src: stablepin.j2
    dest: /etc/apt/preferences.d/stablepin

- name: Install apt https driver
  apt:
    name: apt-transport-https
    state: present

- name: Install nodesource apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add Debian testing apt repository to install Python 3.7
  apt_repository:
    repo: deb http://ftp.fr.debian.org/debian testing main contrib non-free
    state: present
    filename: python

- name: Add nodesource apt repository to install NodeJs
  apt_repository:
    repo: deb https://deb.nodesource.com/node_8.x stretch main
    state: present
    filename: nodesource

- name: Upgrade all packages
  apt:
    upgrade: safe
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - gettext
      - postgresql
      - libpq-dev
      - python-psycopg2
      - python-virtualenv
      - git
      - nginx
      - supervisor
      - nodejs
      - certbot

- name: Install python3.7 (testing)
  apt:
    name: "{{ packages }}"
    state: latest
    default_release: testing
  vars:
    packages:
      - python3.7
      - python3.7-dev
      - python3-pip
      - python3-distutils
      - python3-virtualenv

- name: Install sass
  npm:
    name: sass
    global: yes
