---
- name: Collect static
  django_manage:
    command: collectstatic
    app_path: "{{ django_root }}"
    virtualenv: "{{ venv_dir }}"
    settings: "{{ django_settings }}"

- name: Restart django
  become: no
  supervisorctl: name={{ project_name }} state=restarted

- name: Restart nginx
  become: no
  service:
    name: nginx
    state: restarted

