---
- name: Start redis
  service:
    name: "redis-server"
    state: started

- name: Restart django
  supervisorctl:
    name: "{{ project_name }}"
    state: restarted

- name: Restart minisites
  supervisorctl:
    name: "{{ project_name }}_minisites"
    state: restarted

- name: Restart celery
  supervisorctl:
    name: "celery"
    state: restarted

- name: Restart nginx
  service:
    name: nginx
    state: restarted
