---
- name: Slack
  community.general.slack:
    token: '{{ lookup("env", "SLACK_WEBHOOK_TOKEN") }}'
    msg: 'Déploiement de {{ project_version }} sur {{ inventory_hostname }}.'
  delegate_to: localhost
