---
- name: Create user
  user:
    name: "{{ user_name }}"
    state: present
    password_lock: true

- name: Allow sudo_user to access Ansible's SSH_AUTH_SOCK
  shell: >
    setfacl -m {{ user_name }}:x  $(dirname "$SSH_AUTH_SOCK") ;
    setfacl -m {{ user_name }}:rwx "$SSH_AUTH_SOCK"
  changed_when: false

- name: Create .profile file
  template:
    src: profile.j2
    dest: "{{ install_root }}/.profile"
    owner: "{{ user_name }}"
