---
- name: Create virtualenv directory
  become: yes
  become_user: "{{ user_name }}"
  file:
    path: "{{ venv_root }}"
    state: directory

- name: Create the virtualenv
  become: yes
  become_user: "{{ user_name }}"
  command: virtualenv {{ venv_dir }} -p python3.7
  args:
    creates: "{{ venv_dir }}"

- name: Install pipenv
  become: yes
  become_user: "{{ user_name }}"
  pip:
    name: pipenv
    virtualenv: "{{ venv_dir }}"
