---
- name: Create virtualenv directory
  become: yes
  become_user: "{{ user_name }}"
  file:
    path: "{{ venv_root }}"
    state: directory

- name: Create the virtualenv
  become: yes
  become_user: "{{ user_name }}"
  command: python3 -m venv {{ venv_dir }}
  args:
    creates: "{{ venv_dir }}"

- name: Install pipenv
  become: yes
  become_user: "{{ user_name }}"
  pip:
    name: pipenv
    virtualenv: "{{ venv_dir }}"
    virtualenv_command  : "{{ venv_dir }}/bin/python3 -m venv"
