---
- name: Create supervisor configuration
  template:
    src: supervisor.j2
    dest: /etc/supervisor/conf.d/{{ project_name }}.conf

- name: Create nginx configuration
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/{{ project_name }}

- name: Create nginx symlink
  file:
    src: /etc/nginx/sites-available/{{ project_name }}
    dest: /etc/nginx/sites-enabled/{{ project_name }}
    state: link
