---
- name: Create supervisor configuration
  template:
    src: supervisor.j2
    dest: /etc/supervisor/conf.d/{{ project_name }}.conf

- name: Create minisites supervisor configuration
  template:
    src: supervisor_minisites.j2
    dest: /etc/supervisor/conf.d/{{ project_name }}_minisites.conf

- name: Create nginx configuration
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/{{ project_name }}

- name: Create nginx symlink
  file:
    src: /etc/nginx/sites-available/{{ project_name }}
    dest: /etc/nginx/sites-enabled/{{ project_name }}
    state: link

- name: Create nginx configuration (default)
  template:
    src: nginx_default.j2
    dest: /etc/nginx/sites-available/default

- name: Remove default host symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
