# Generated by Django 3.2.4 on 2021-06-14 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_page_minisite"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date created"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Date updated"),
        ),
    ]
