# Generated by Django 3.2.16 on 2022-12-20 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0011_auto_20221123_1400"),
        ("pages", "0005_page_minisite_related_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tab",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu de l'onglet")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Programme lié à cette page.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pages",
                        to="programs.program",
                        verbose_name="Program",
                    ),
                ),
            ],
        ),
    ]
