# Generated by Django 4.1.5 on 2023-01-13 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0013_alter_programtab_options"),
        ("pages", "0006_tab"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=600, verbose_name="Nom")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Rang")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Programme lié à cette rubrique.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faqcategory",
                        to="programs.program",
                        verbose_name="Programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubrique de la FAQ",
                "verbose_name_plural": "Rubriques de la FAQ",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="FaqQuestionAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=180, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Réponse")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Rang")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "faq_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rubrique liée à cette Question-Réponse",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faqquestionanswer",
                        to="pages.faqcategory",
                        verbose_name="Rubrique",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Programme lié à cette Question-Réponse",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faqquestionanswer",
                        to="programs.program",
                        verbose_name="Programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question-Réponse de la FAQ",
                "verbose_name_plural": "Question-Réponse de la FAQ",
                "ordering": ["faq_category", "order"],
            },
        ),
    ]
