# Generated by Django 4.2.3 on 2023-08-04 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0041_alter_searchpage_available_audiences_and_more"),
        ("pages", "0007_faqcategory_faqquestionanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Le titre qui sera affiché dans les SERPs.\n        Il est recommandé de le garder <\xa0120 caractères.",
                max_length=256,
                verbose_name="Description (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Le titre qui sera affiché dans les SERPs.\n        Il est recommandé de le garder <\xa060 caractères. Laissez vide pour\n        réutiliser le titre de la page.",
                max_length=180,
                verbose_name="Titre (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="minisite",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionnel, lie cette page à un minisite.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pages",
                to="search.searchpage",
                verbose_name="Minisite",
            ),
        ),
        migrations.AlterField(
            model_name="tab",
            name="content",
            field=models.TextField(verbose_name="Contenu de l’onglet"),
        ),
        migrations.AlterField(
            model_name="tab",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="tab",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
    ]
