# Generated by Django 2.1.2 on 2018-11-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_auto_20181114_1019"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
    ]
