# Generated by Django 2.1.2 on 2018-11-15 09:03

import core.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_remove_tag_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=core.indexes.GinTrigramIndex(fields=['name'], name='tags_tag_name_fe221d_gin'),
        ),
    ]
