# Generated by Django 4.1.7 on 2023-02-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0005_auto_20190410_0935"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
