# Generated by Django 3.2.4 on 2021-07-01 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dataproviders", "0002_cleanup_choices_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="aid_author",
            field=models.ForeignKey(
                help_text="Admin AT si vide",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_aid_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="L'auteur par défaut de l'aide importée",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="contact_team",
            field=models.ForeignKey(
                limit_choices_to={"is_superuser": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_contact_team",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contact AT team",
            ),
        ),
    ]
