# Generated by Django 3.2.6 on 2021-08-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aids', '0146_auto_20210806_1549'),
        ('projects', '0005_auto_20210430_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_suggested',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='aids_associated',
            field=models.ManyToManyField(blank=True, to='aids.Aid', verbose_name='Aids'),
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
    ]
