# Generated by Django 3.2.6 on 2021-08-25 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20210820_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beneficiary',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs'),
        ),
    ]
