# Generated by Django 3.2.6 on 2021-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_remove_unused_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'échéance"
            ),
        ),
    ]
