# Generated by Django 3.2.6 on 2021-09-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0007_project_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='organizations.Organization', verbose_name='Structures'),
        ),
    ]
