# Generated by Django 3.2.15 on 2022-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_synonymlist_model'),
        ('projects', '0011_translate_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publié?'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_types',
            field=models.ManyToManyField(blank=True, to='keywords.SynonymList', verbose_name='Types de projet'),
        ),
    ]
