# Generated by Django 3.2.15 on 2022-09-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_public_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_link',
            field=models.CharField(blank=True, choices=[('CRTE', 'CRTE')], max_length=10, null=True, verbose_name='Appartenance à un plan/programme/contrat'),
        ),
    ]
