# Generated by Django 3.2.15 on 2022-10-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_public_projects_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_link',
            field=models.CharField(blank=True, choices=[('CRTE', 'CRTE'), ('PVD', 'Petites Villes de Demain'), ('ACV1', 'Action Coeur de Ville 1'), ('ACV2', 'Action Coeur de Ville 2'), ('PCAET', 'PCAET')], max_length=10, null=True, verbose_name='Appartenance à un plan/programme/contrat'),
        ),
    ]
