# Generated by Django 3.2.16 on 2022-11-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_public_projects_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='due_date',
        ),
        migrations.AddField(
            model_name='project',
            name='step',
            field=models.CharField(blank=True, choices=[('considered', 'En réflexion'), ('ongoing', 'En cours'), ('finished', 'Réalisé')], max_length=10, null=True, verbose_name='Avancement du projet'),
        ),
    ]
