# Generated by Django 3.2.15 on 2022-09-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_contract_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private_description',
            field=models.TextField(blank=True, default='', verbose_name='Description privée du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description publique du projet'),
        ),
    ]
