# Generated by Django 3.2.16 on 2022-11-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_add_field_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget prévisionnel'),
        ),
    ]
