# Generated by Django 3.2.16 on 2022-11-24 15:35

from django.db import migrations
import django_resized.forms
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_budget_and_step_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="PNG",
                keep_meta=False,
                null=True,
                quality=100,
                scale=None,
                size=[714, 450],
                upload_to=projects.models.image_upload_to,
            ),
        ),
    ]
