# Generated by Django 4.1.5 on 2023-01-24 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_organization_imported_date_organization_is_imported"),
        ("backers", "0015_backer_perimeter"),
        ("aids", "0174_alter_aidproject_aid_alter_aidproject_project"),
        ("projects", "0015_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidatedProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aid_unknown",
                    models.CharField(
                        max_length=600,
                        verbose_name="Nom de l'aide non présente en base",
                    ),
                ),
                (
                    "project_unknown",
                    models.CharField(
                        max_length=1000,
                        verbose_name="Nom du projet non présent en base",
                    ),
                ),
                (
                    "financer_unknown",
                    models.CharField(
                        max_length=600,
                        verbose_name="Porteur de l'aide obtenue inconnu en base",
                    ),
                ),
                (
                    "final_budget",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Budget définitif"
                    ),
                ),
                (
                    "amount_obtained",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Montant obtenu"
                    ),
                ),
                (
                    "date_obtention",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date à laquelle l'aide a été obtenue par le porteur du projet",
                        null=True,
                        verbose_name="Date de l'obtention",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de création de l'objet",
                        null=True,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "aid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aids.aid",
                        verbose_name="Aide liée",
                    ),
                ),
                (
                    "financer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backers.backer",
                        verbose_name="Porteur de l'aide obtenue",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                        verbose_name="Organisation porteuse",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.project",
                        verbose_name="Projet lié",
                    ),
                ),
            ],
        ),
    ]
