# Generated by Django 4.1.5 on 2023-01-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="final_budget",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Budget définitif"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_imported",
            field=models.BooleanField(default=False, verbose_name="Importé\xa0?"),
        ),
        migrations.AlterField(
            model_name="project",
            name="step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("considered", "En réflexion"),
                    ("ongoing", "En cours"),
                    ("finished", "Réalisé"),
                    ("validated", "Validé"),
                ],
                max_length=10,
                null=True,
                verbose_name="Avancement du projet",
            ),
        ),
    ]
