# Generated by Django 4.1.5 on 2023-01-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="final_budget",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Budget définitif"
            ),
        ),
    ]
