# Generated by Django 3.2.16 on 2022-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='other_project_owner',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name="Autre maître d'ouvrage"),
        ),
    ]
