# Generated by Django 4.1.5 on 2023-01-25 10:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0015_backer_perimeter"),
        ("organizations", "0009_organization_imported_date_organization_is_imported"),
        ("aids", "0173_aid_import_updated"),
        ("projects", "0015_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidatedProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=255, verbose_name="Nom du projet"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description du projet"
                    ),
                ),
                (
                    "aid_name",
                    models.CharField(max_length=180, verbose_name="Nom de l'aide"),
                ),
                (
                    "financer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nom du porteur de l'aide obtenue",
                    ),
                ),
                (
                    "budget",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Budget définitif"
                    ),
                ),
                (
                    "amount_obtained",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Montant obtenu"
                    ),
                ),
                (
                    "date_obtained",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date à laquelle l'aide a été obtenue par le porteur du projet",
                        null=True,
                        verbose_name="Date de l'obtention",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "search_vector_unaccented_validated_project",
                    django.contrib.postgres.search.SearchVectorField(
                        null=True,
                        verbose_name="Search vector unaccented_validated_project",
                    ),
                ),
                (
                    "aid_linked",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aids.aid",
                        verbose_name="Aide liée",
                    ),
                ),
                (
                    "financer_linked",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backers.backer",
                        verbose_name="Porteur d'aides lié",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                        verbose_name="Organisation porteuse",
                    ),
                ),
                (
                    "project_linked",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                        verbose_name="Projet lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet subventionné",
                "verbose_name_plural": "Projets subventionnés",
                "ordering": ["project_name"],
            },
        ),
        migrations.AddIndex(
            model_name="validatedproject",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector_unaccented_validated_project"],
                name="projects_va_search__8f658c_gin",
            ),
        ),
    ]
