# Generated by Django 4.2.2 on 2023-06-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_alter_project_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="contract_link",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACV1", "Action Coeur de Ville 1"),
                    ("ACV2", "Action Coeur de Ville 2"),
                    (
                        "AMI",
                        "AMI pour l’égalité entre les femmes et les hommes dans les territoires ruraux",
                    ),
                    ("CRTE", "CRTE"),
                    ("PCAET", "PCAET"),
                    ("PVD", "Petites Villes de Demain"),
                ],
                max_length=10,
                null=True,
                verbose_name="Appartenance à un plan/programme/contrat",
            ),
        ),
    ]
