# Generated by Django 4.1.5 on 2023-01-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_validatedproject_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="validatedproject",
            unique_together={
                (
                    "project_name",
                    "aid_name",
                    "financer_name",
                    "amount_obtained",
                    "date_obtained",
                )
            },
        ),
    ]
