# Generated by Django 4.1.5 on 2023-01-27 10:07

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_alter_validatedproject_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="validatedproject",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="validatedproject",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("project_name"),
                django.db.models.functions.text.Lower("aid_name"),
                models.F("financer_name"),
                models.F("amount_obtained"),
                models.F("date_obtained"),
                name="unique_projectname_aidname_financername_amount_date",
            ),
        ),
    ]
