# Generated by Django 4.1.5 on 2023-01-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0015_backer_perimeter"),
        ("projects", "0018_alter_validatedproject_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validatedproject",
            name="import_uniqueid",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Identifiant d’import unique",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d’échéance"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="other_project_owner",
            field=models.CharField(
                blank=True,
                max_length=180,
                null=True,
                verbose_name="Autre maître d’ouvrage",
            ),
        ),
        migrations.AlterField(
            model_name="validatedproject",
            name="aid_name",
            field=models.CharField(max_length=180, verbose_name="Nom de l’aide"),
        ),
        migrations.AlterField(
            model_name="validatedproject",
            name="date_obtained",
            field=models.DateTimeField(
                blank=True,
                help_text="Date à laquelle l’aide a été obtenue par le porteur du projet",
                null=True,
                verbose_name="Date de l’obtention",
            ),
        ),
        migrations.AlterField(
            model_name="validatedproject",
            name="financer_linked",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backers.backer",
                verbose_name="Porteur d’aides lié",
            ),
        ),
        migrations.AlterField(
            model_name="validatedproject",
            name="financer_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Nom du porteur de l’aide obtenue",
            ),
        ),
    ]
