# Generated by Django 2.2.1 on 2019-10-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0002_auto_20180921_1056"),
    ]

    operations = [
        migrations.AddField(
            model_name="backer",
            name="is_corporate",
            field=models.BooleanField(
                default=False, verbose_name="Is a corporate backer?"
            ),
        ),
    ]
