# Generated by Django 2.2.12 on 2020-04-21 10:10

from django.db import migrations
from django.utils.text import slugify


def set_slugs(apps, schema_editor):
    Backer = apps.get_model("backers", "Backer")
    for backer in Backer.objects.all():
        backer.slug = slugify(backer.name)[:50]
        backer.save()


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0004_backer_slug"),
    ]

    operations = [migrations.RunPython(set_slugs)]
