# Generated by Django 2.2.17 on 2020-12-01 13:01

import backers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backers', '0006_add_slug_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='backer',
            name='logo',
            field=models.FileField(blank=True, help_text='Make sure the file is not too heavy. Prefer svg files.', null=True, upload_to=backers.models.logo_upload_to, verbose_name='Logo image'),
        ),
        migrations.AddField(
            model_name='backer',
            name='logo_link',
            field=models.URLField(blank=True, help_text="The url for the backer's logo link", null=True, verbose_name='Logo link'),
        ),
    ]
