# Generated by Django 2.2.17 on 2020-12-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backers', '0007_auto_20201201_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='backer',
            name='logo_in_Home_page',
            field=models.BooleanField(default=False, verbose_name='logo in the Homepage?'),
        ),
    ]
