# Generated by Django 2.2.17 on 2020-12-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backers', '0006_add_slug_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backer',
            name='slug',
            field=models.SlugField(blank=True, help_text='Let it empty so it will be autopopulated.', verbose_name='Slug'),
        ),
    ]
