# Generated by Django 2.2.17 on 2021-01-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0011_auto_20210104_1722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backer",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="Full description of the backer"
            ),
        ),
    ]
