# Generated by Django 2.2.17 on 2021-01-19 18:42

from django.db import migrations
from django.utils.text import slugify


def fix_backers_slug_length(apps, schema_editor):
    Backer = apps.get_model("backers", "Backer")
    backers = Backer.objects.all()
    for backer in backers:
        if backer.slug:
            backer.slug = backer.slug[:50]
        else:
            backer.slug = slugify(backer.name)[:50]
        backer.save()


def fix_backergroups_slug_length(apps, schema_editor):
    BackerGroup = apps.get_model("backers", "BackerGroup")
    backergroups = BackerGroup.objects.all()
    for backergroup in backergroups:
        if backergroup.slug:
            backergroup.slug = backergroup.slug[:50]
        else:
            backergroup.slug = slugify(backergroup.name)[:50]
        backergroup.save()


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0012_edit_description_field"),
    ]

    operations = [
        migrations.RunPython(fix_backers_slug_length),
        migrations.RunPython(fix_backergroups_slug_length),
    ]
