# Generated by Django 3.1.7 on 2021-02-23 13:08

from django.db import migrations
from django.db.migrations.operations.special import RunPython
from django.core.files.storage import FileSystemStorage


def reupload_files(apps, schema_editor):
    Backer = apps.get_model('backers', 'Backer')
    fs_storage = FileSystemStorage()

    for backer in Backer.objects.all():
        file_name = backer.logo.name
        if file_name and fs_storage.exists(file_name):
            field_file = fs_storage.open(file_name)
            backer.logo = field_file
            backer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backers', '0013_fix_slug_length'),
    ]

    operations = [
        RunPython(reupload_files, RunPython.noop)
    ]
