# Generated by Django 3.2.4 on 2021-07-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0034_cleanup_choices_translations"),
        ("backers", "0014_reupload_medias"),
    ]

    operations = [
        migrations.AddField(
            model_name="backer",
            name="perimeter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="geofr.perimeter",
                verbose_name="Périmètre",
            ),
        ),
    ]
