# Generated by Django 4.2.1 on 2023-05-23 13:12

import backers.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0015_backer_perimeter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backer",
            options={
                "verbose_name": "Porteur d’aides",
                "verbose_name_plural": "Porteurs d’aides",
            },
        ),
        migrations.AlterModelOptions(
            name="backergroup",
            options={
                "verbose_name": "Groupe de porteurs",
                "verbose_name_plural": "Groupes de porteurs",
            },
        ),
        migrations.AlterField(
            model_name="backer",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="backer",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Description complète du porteur d’aides",
            ),
        ),
        migrations.AlterField(
            model_name="backer",
            name="external_link",
            field=models.URLField(
                blank=True,
                help_text="L’URL externe vers laquelle renvoie un clic sur le logo du porteur",
                null=True,
                verbose_name="Lien externe",
            ),
        ),
        migrations.AlterField(
            model_name="backer",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backers",
                to="backers.backergroup",
                verbose_name="Groupe de porteurs",
            ),
        ),
        migrations.AlterField(
            model_name="backer",
            name="is_corporate",
            field=models.BooleanField(
                default=False, verbose_name="Porteur d'aides privé\xa0?"
            ),
        ),
        migrations.AlterField(
            model_name="backer",
            name="is_spotlighted",
            field=models.BooleanField(
                default=False,
                help_text="Si le porteur est mis en avant, son logo apparaît sur la page d’accueil",
                verbose_name="Le porteur est-il mis en avant\xa0?",
            ),
        ),
        migrations.AlterField(
            model_name="backer",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Évitez les fichiers trop lourds. Préférez les fichiers SVG.",
                null=True,
                upload_to=backers.models.logo_upload_to,
                verbose_name="Logo du porteur",
            ),
        ),
        migrations.AlterField(
            model_name="backer",
            name="meta_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Sera affichée dans les SERPs. À garder <\xa0120 caractères.",
                max_length=256,
                verbose_name="Description (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="backer",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Le titre qui sera affiché dans les SERPs.\n        Il est recommandé de le garder <\xa060 caractères.\n        Laissez vide pour réutiliser le nom du porteur d’aides.",
                max_length=180,
                verbose_name="Titre (balise meta)",
            ),
        ),
        migrations.AlterField(
            model_name="backer",
            name="name",
            field=models.CharField(db_index=True, max_length=256, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="backer",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Laisser vide pour autoremplir.",
                verbose_name="Fragment d’URL",
            ),
        ),
        migrations.AlterField(
            model_name="backergroup",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="backergroup",
            name="name",
            field=models.CharField(db_index=True, max_length=256, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="backergroup",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Laisser vide pour autoremplir.",
                verbose_name="Fragment d’URL",
            ),
        ),
    ]
