# Generated by Django 4.2.2 on 2023-06-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0016_backercategory_alter_backer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backer",
            name="meta_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Le titre qui sera affiché dans les SERPs.\n        Il est recommandé de le garder < 60 caractères.\n        Laissez vide pour réutiliser le nom du porteur d’aides.",
                max_length=180,
                verbose_name="Titre (balise meta)",
            ),
        ),
    ]
