# Generated by Django 4.2.4 on 2023-08-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backers", "0017_alter_backer_meta_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backer",
            options={
                "verbose_name": "Porteur d’aides",
                "verbose_name_plural": "Porteurs d’aides",
            },
        ),
        migrations.AlterModelOptions(
            name="backersubcategory",
            options={
                "verbose_name": "Sous-catégorie de porteurs",
                "verbose_name_plural": "Sous-catégories de porteurs",
            },
        ),
        migrations.AlterField(
            model_name="backer",
            name="is_spotlighted",
            field=models.BooleanField(
                default=False,
                help_text="Si le porteur est mis en avant, son logo apparaît sur la page d’accueil",
                verbose_name="Le porteur est-il mis en avant\xa0?",
            ),
        ),
        migrations.AlterField(
            model_name="backer",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Laisser vide pour autoremplir.",
                verbose_name="Fragment d’URL",
            ),
        ),
    ]
