# Generated by Django 2.1.2 on 2018-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20181115_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ml_consent",
            field=models.BooleanField(
                default=False, verbose_name="Gave consent to receive communications"
            ),
        ),
    ]
