# Generated by Django 2.1.5 on 2019-01-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_watched_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=35, verbose_name="Contact phone number"
            ),
        ),
    ]
