# Generated by Django 2.2.16 on 2020-10-28 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_update_emails_to_lowercase'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('ml_consent', models.BooleanField(default=True, verbose_name='Gave consent to receive communications')),
            ],
            options={
                'verbose_name': 'NewsletterUser',
                'verbose_name_plural': 'NewsletterUsers',
            },
        ),
    ]
