# Generated by Django 2.2.5 on 2021-02-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_auto_20201124_1023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=256, verbose_name="Last name"),
        ),
    ]
