# Generated by Django 3.2.4 on 2021-07-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_user_watched_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="date_joined",
            new_name="date_created",
        ),
    ]
