# Generated by Django 3.2.4 on 2021-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_user_date_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="similar_aids_alert",
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=35, verbose_name="Numéro de téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Adresse e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=256, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_certified",
            field=models.BooleanField(
                default=False,
                help_text="Afficher un badge à côté des aides publiées par ce compte.",
                verbose_name="Certifié\xa0?",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_contributor",
            field=models.BooleanField(
                default=True,
                help_text="Peut accéder à un espace pour créer et modifier ses aides.",
                verbose_name="Contributeur ?",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=256, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="user",
            name="ml_consent",
            field=models.BooleanField(
                default=False,
                verbose_name="A donné son consentement pour recevoir l'actualité",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Organisme"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, max_length=128, verbose_name="Rôle"),
        ),
    ]
