# Generated by Django 3.2.4 on 2021-07-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0034_cleanup_choices_translations"),
        ("accounts", "0016_cleanup_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="animator_perimeter",
            field=models.ForeignKey(
                blank=True,
                help_text="Sur quel périmètre l'animateur local est-il responsable ?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animators",
                to="geofr.perimeter",
                verbose_name="Périmètre d'animation",
            ),
        ),
    ]
