# Generated by Django 3.2.4 on 2021-07-16 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backers', '0014_reupload_medias'),
        ('accounts', '0016_cleanup_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backer',
            field=models.ForeignKey(blank=True, help_text="Rattacher un contributeur à un porteur d'aides lui permettra de voir les aides de ses collègues.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributors', to='backers.backer', verbose_name="Porteur d'aides"),
        ),
    ]
