# Generated by Django 3.2.6 on 2021-08-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('accounts', '0017_user_animator_perimeter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_phone',
            new_name='contributor_contact_phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='organization',
            new_name='contributor_organization',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='contributor_role',
        ),
        migrations.AddField(
            model_name='user',
            name='beneficiary_organization',
            field=models.ForeignKey(blank=True, help_text='A quelle structure appartient le bénéficiaire ?', null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Structure du bénéficiaire'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_beneficiary',
            field=models.BooleanField(default=True, help_text='Peut accéder à un espace pour créer et modifier ses projets.', verbose_name='Bénéficiaire ?'),
        ),
    ]
