# Generated by Django 3.2.6 on 2021-10-01 11:31

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_user_beneficiary_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="beneficiary_function",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("elected", "Élu"),
                        ("agent", "Agent territorial"),
                        ("other", "Autre"),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Fonction du bénéficiaire",
            ),
        ),
    ]
