# Generated by Django 3.2.6 on 2022-01-17 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_beneficiary_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLastConnexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_connexion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la dernière connexion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Dernière connexion de l'utilisateur",
                'verbose_name_plural': 'Dernières connexions des utilisateurs',
            },
        ),
    ]
