# Generated by Django 3.2.13 on 2022-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_invitation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_organization_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation de l'invitation"),
        ),
    ]
