# Generated by Django 3.2.14 on 2022-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_acquisition',
            field=models.CharField(blank=True, choices=[('webinar', 'Webinaire de démo'), ('thematic-webinar', 'Webinaire thématique'), ('animator', 'Animateur local'), ('trade-press', 'Presse spécialisée'), ('association', 'Association'), ('elected', 'Élu'), ('invited', 'Invitation à collaborer'), ('other', 'Autre')], help_text="Comment l'utilisateur a-t-il connu Aides-territoires?", max_length=32, null=True, verbose_name="Canal d'acquisition"),
        ),
    ]
