# Generated by Django 3.2.15 on 2022-09-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_alter_user_beneficiary_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="beneficiary_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mayor", "Maire"),
                    ("deputy_mayor", "Adjoint au maire"),
                    ("municipal_councilor", "Conseiller municipal"),
                    ("elected", "Élu"),
                    ("town_clerk", "Secrétaire de mairie"),
                    ("agent", "Agent territorial"),
                    ("other", "Autre"),
                ],
                max_length=32,
                null=True,
                verbose_name="Fonction du bénéficiaire",
            ),
        ),
    ]
