# Generated by Django 4.1.5 on 2023-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_alter_user_beneficiary_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_aid_team",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification interne uniquement"),
                    ("internal_email", "Notification interne et par email"),
                ],
                default="internal_email",
                help_text="Notifications liées aux aides envoyées à tous les membres de la structure",
                max_length=32,
                verbose_name="Notifications aides équipe",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_aid_user",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification interne uniquement"),
                    ("internal_email", "Notification interne et par email"),
                ],
                default="internal_email",
                help_text="Notifications liées aux aides concernant l’utilisateur",
                max_length=32,
                verbose_name="Notifications aides individuelles",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de notifications reçues"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_email_frequency",
            field=models.CharField(
                choices=[("daily", "Quotidienne"), ("weekly", "Hebdomadaire")],
                default="daily",
                max_length=32,
                verbose_name="Fréquence d’envoi des emails de notification",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_generic_team",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification interne uniquement"),
                    ("internal_email", "Notification interne et par email"),
                ],
                default="internal_email",
                help_text="Notifications génériques envoyées à tous les membres de la structure",
                max_length=32,
                verbose_name="Notifications génériques équipe",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_generic_user",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification interne uniquement"),
                    ("internal_email", "Notification interne et par email"),
                ],
                default="internal_email",
                help_text="Notifications internes concernant l’utilisateur",
                max_length=32,
                verbose_name="Notifications génériques individuelles",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="acquisition_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("webinar", "Webinaire"),
                    ("animator", "Animateur local"),
                    ("trade_press", "Presse spécialisée"),
                    ("word_of_mouth", "Bouche-à-oreille"),
                    ("invited", "Invitation à collaborer"),
                    ("other", "Autre"),
                ],
                help_text="Comment l’utilisateur a-t-il connu Aides-territoires?",
                max_length=32,
                null=True,
                verbose_name="Canal d’acquisition",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="acquisition_channel_comment",
            field=models.CharField(
                blank=True,
                help_text="Comment l’utilisateur a-t-il connu Aides-territoires (champ libre)?",
                max_length=1000,
                null=True,
                verbose_name="Commentaire Canal d’acquisition",
            ),
        ),
    ]
