# Generated by Django 3.2.16 on 2022-12-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_alter_user_beneficiary_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_aid_team",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification interne uniquement"),
                    ("internal_email", "Notification interne et par email"),
                ],
                default="internal_email",
                help_text="Notifications liées aux aides envoyées à tous les membres de la structure",
                max_length=32,
                verbose_name="Notifications aides équipe",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_aid_user",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification interne uniquement"),
                    ("internal_email", "Notification interne et par email"),
                ],
                default="internal_email",
                help_text="Notifications liées aux aides concernant l’utilisateur",
                max_length=32,
                verbose_name="Notifications aides individuelles",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_internal_team",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification interne uniquement"),
                    ("internal_email", "Notification interne et par email"),
                ],
                default="internal_email",
                help_text="Notifications internes envoyées à tous les membres de la structure",
                max_length=32,
                verbose_name="Notifications internes équipe",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_internal_user",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification interne uniquement"),
                    ("internal_email", "Notification interne et par email"),
                ],
                default="internal_email",
                help_text="Notifications internes concernant l’utilisateur",
                max_length=32,
                verbose_name="Notifications interne individuelles",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="acquisition_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("webinar", "Webinaire"),
                    ("animator", "Animateur local"),
                    ("trade_press", "Presse spécialisée"),
                    ("word_of_mouth", "Bouche-à-oreille"),
                    ("invited", "Invitation à collaborer"),
                    ("other", "Autre"),
                ],
                help_text="Comment l’utilisateur a-t-il connu Aides-territoires?",
                max_length=32,
                null=True,
                verbose_name="Canal d’acquisition",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="acquisition_channel_comment",
            field=models.CharField(
                blank=True,
                help_text="Comment l’utilisateur a-t-il connu Aides-territoires (champ libre)?",
                max_length=1000,
                null=True,
                verbose_name="Commentaire Canal d’acquisition",
            ),
        ),
    ]
