# Generated by Django 4.1.5 on 2023-01-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_user_notification_aid_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notification_aid_team",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification en ligne uniquement"),
                    ("internal_email", "Notification en ligne et par email"),
                ],
                default="internal_email",
                help_text="Notifications liées aux aides envoyées à tous les membres de la structure",
                max_length=32,
                verbose_name="Notifications aides équipe",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notification_aid_user",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification en ligne uniquement"),
                    ("internal_email", "Notification en ligne et par email"),
                ],
                default="internal_email",
                help_text="Notifications liées aux aides concernant l’utilisateur",
                max_length=32,
                verbose_name="Notifications aides individuelles",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notification_email_frequency",
            field=models.CharField(
                choices=[("daily", "Quotidienne"), ("weekly", "Hebdomadaire")],
                default="daily",
                max_length=32,
                verbose_name="Fréquence d’envoi des emails de notifications",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notification_generic_team",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification en ligne uniquement"),
                    ("internal_email", "Notification en ligne et par email"),
                ],
                default="internal_email",
                help_text="Notifications génériques envoyées à tous les membres de la structure",
                max_length=32,
                verbose_name="Notifications génériques équipe",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notification_generic_user",
            field=models.CharField(
                choices=[
                    ("none", "Aucune"),
                    ("internal_only", "Notification en ligne uniquement"),
                    ("internal_email", "Notification en ligne et par email"),
                ],
                default="internal_email",
                help_text="Notifications internes concernant l’utilisateur",
                max_length=32,
                verbose_name="Notifications génériques individuelles",
            ),
        ),
    ]
