# Generated by Django 4.2.5 on 2023-10-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0033_user_notification_counter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_project_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Merci de décrire précisément l’usage que vous allez avoir de l’API Aides-territoires",
                verbose_name="Description de votre projet",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="api_project_url",
            field=models.URLField(
                blank=True,
                help_text="Entrez ici l’URL de votre service le cas échéant",
                max_length=700,
                verbose_name="URL de votre service",
            ),
        ),
    ]
