# Generated by Django 3.2.16 on 2022-12-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_auto_20221214_1554"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_email_frequency",
            field=models.CharField(
                choices=[("daily", "Quotidienne"), ("weekly", "Hebdomadaire")],
                default="daily",
                max_length=32,
                verbose_name="Fréquence d’envoi des emails de notification",
            ),
        ),
    ]
