# Generated by Django 3.2.16 on 2022-12-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_user_notification_email_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de notifications reçues"
            ),
        ),
    ]
