# Generated by Django 2.2.9 on 2020-03-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_import_bookmarks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
            },
        ),
    ]
