# Generated by Django 3.1.7 on 2021-03-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_auto_20200302_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="source",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="Source"
            ),
        ),
    ]
