# Generated by Django 3.2.4 on 2021-06-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0005_alert_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_frequency",
            field=models.CharField(
                choices=[("daily", "Quotidiennement"), ("weekly", "Hebdomadairement")],
                default="daily",
                max_length=32,
            ),
        ),
    ]
