# Generated by Django 4.2.3 on 2023-08-04 10:59

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_squashed_0006_cleanup_choices_translations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
            },
        ),
        migrations.AlterField(
            model_name="alert",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="date_validated",
            field=models.DateTimeField(null=True, verbose_name="Date de validation"),
        ),
        migrations.AlterField(
            model_name="alert",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Courriel"),
        ),
        migrations.AlterField(
            model_name="alert",
            name="latest_alert_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Dernière alerte"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="alert",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Clé secrète",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="validated",
            field=models.BooleanField(default=False, verbose_name="Confirmée\xa0?"),
        ),
    ]
