# Generated by Django 3.2.12 on 2022-04-25 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nom')),
                ('slug', models.SlugField(verbose_name="Fragment d'url")),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Mot clé',
                'verbose_name_plural': 'Mots clé',
                'ordering': ['-date_created'],
            },
        ),
    ]
