# Generated by Django 3.2.14 on 2022-08-29 08:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SynonymList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=70, verbose_name="Nom de la liste"),
                ),
                ("slug", models.SlugField(verbose_name="Fragment d'url")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "keywords_list",
                    models.CharField(
                        blank=True,
                        help_text="La liste de mots clés correspond à une liste de synonymes,         et termes du champ lexical associé.",
                        max_length=1800,
                        null=True,
                        verbose_name="liste de mots clés",
                    ),
                ),
                (
                    "search_vector_keywords_list",
                    django.contrib.postgres.search.SearchVectorField(
                        null=True,
                        verbose_name="liste de mots clés sans accents (Pour indexation)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste de synonymes",
                "verbose_name_plural": "Listes de synonymes",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="synonymlist",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector_keywords_list"],
                name="keywords_sy_search__9ffeb5_gin",
            ),
        ),
    ]
