# Generated by Django 3.2.14 on 2022-08-17 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynonymList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nom de la liste')),
                ('slug', models.SlugField(verbose_name="Fragment d'url")),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('keywords', models.ManyToManyField(blank=True, related_name='synonymList', to='keywords.Keyword', verbose_name='Mots clé')),
            ],
            options={
                'verbose_name': 'Liste de synonymes',
                'verbose_name_plural': 'Listes de synonymes',
                'ordering': ['name'],
            },
        ),
    ]
