# Generated by Django 3.2.14 on 2022-08-19 06:19

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_synonymlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonymlist',
            name='unaccented_keywords_list',
            field=models.CharField(blank=True, max_length=1800, null=True, verbose_name='liste de mots clés sans accents (Pour indexation)'),
        ),
        migrations.AlterField(
            model_name='synonymlist',
            name='keywords_list',
            field=models.CharField(blank=True, max_length=1800, null=True, verbose_name='liste de mots clés'),
        ),
        migrations.AddIndex(
            model_name='synonymlist',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords_list'], name='keywords_list_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='synonymlist',
            index=django.contrib.postgres.indexes.GinIndex(fields=['unaccented_keywords_list'], name='unaccented_keywords_list_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
