# Generated by Django 3.2.6 on 2021-08-20 12:59

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geofr', '0034_cleanup_choices_translations'),
        ('projects', '0005_auto_20210430_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, help_text='Laisser vide pour autoremplir.', verbose_name="Fragment d'URL")),
                ('organization_type', core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('commune', 'Communes'), ('epci', 'EPCI à fiscalité propre'), ('department', 'Départements'), ('region', 'Régions'), ('special', "Collectivités d'outre-mer à statuts particuliers"), ('association', 'Associations'), ('private_person', 'Particuliers'), ('farmer', 'Agriculteurs'), ('private_sector', 'Entreprises privées'), ('public_cies', 'Entreprises publiques locales (Sem, Spl, SemOp)'), ('public_org', "Établissements publics (écoles, bibliothèques…) / Services de l'État"), ('researcher', 'Recherche')], max_length=32), blank=True, null=True, size=None, verbose_name='Type de structure')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('beneficiaries', models.ManyToManyField(blank=True, related_name='Organization', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaires')),
                ('perimeter', models.ForeignKey(blank=True, help_text='Sur quel périmètre la structure intervient-elle ?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization', to='geofr.perimeter', verbose_name='Périmètre de la structure')),
                ('projects', models.ManyToManyField(blank=True, related_name='Organization', to='projects.Project', verbose_name='Projets')),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
            },
        ),
    ]
