# Generated by Django 3.2.6 on 2021-11-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="ape_code",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Code APE"
            ),
        ),
    ]
