# Generated by Django 3.2.6 on 2021-08-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210820_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Adresse postale'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ape_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code APE'),
        ),
        migrations.AddField(
            model_name='organization',
            name='associations_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'associations"),
        ),
        migrations.AddField(
            model_name='organization',
            name='cemetery_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de cimetières'),
        ),
        migrations.AddField(
            model_name='organization',
            name='city_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nom de la ville'),
        ),
        migrations.AddField(
            model_name='organization',
            name='corporates_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'entreprises"),
        ),
        migrations.AddField(
            model_name='organization',
            name='departmental_roads',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Routes départementales (kms)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='gymnasium_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de gymnases et salles de sport'),
        ),
        migrations.AddField(
            model_name='organization',
            name='high_school_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de lycées'),
        ),
        migrations.AddField(
            model_name='organization',
            name='inhabitants_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'habitants"),
        ),
        migrations.AddField(
            model_name='organization',
            name='kindergarten_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'écoles maternelles"),
        ),
        migrations.AddField(
            model_name='organization',
            name='lamppost_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de lampadaires'),
        ),
        migrations.AddField(
            model_name='organization',
            name='library_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de bibliothèques'),
        ),
        migrations.AddField(
            model_name='organization',
            name='medialibrary_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de mediathèques'),
        ),
        migrations.AddField(
            model_name='organization',
            name='middle_school_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de collèges'),
        ),
        migrations.AddField(
            model_name='organization',
            name='municipal_roads',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Routes communales (kms)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='museum_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de musées'),
        ),
        migrations.AddField(
            model_name='organization',
            name='place_of_worship_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de lieux de cultes'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_school_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'écoles primaires"),
        ),
        migrations.AddField(
            model_name='organization',
            name='siren_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code SIREN'),
        ),
        migrations.AddField(
            model_name='organization',
            name='siret_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code SIRET'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sports_ground_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de stades et structures extérieures'),
        ),
        migrations.AddField(
            model_name='organization',
            name='swimming_pool_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de piscines'),
        ),
        migrations.AddField(
            model_name='organization',
            name='theater_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de théâtres'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tram_roads',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tramways (kms)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='university_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'universités"),
        ),
        migrations.AddField(
            model_name='organization',
            name='voters_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de votants'),
        ),
        migrations.AddField(
            model_name='organization',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Code postal'),
        ),
    ]
