# Generated by Django 3.2.6 on 2021-11-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_siren_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='siret_code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Code SIRET'),
        ),
    ]
