# Generated by Django 3.2.15 on 2022-09-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_alter_organization_organization_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="projects",
        ),
    ]
