# Generated by Django 3.2.13 on 2022-07-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0038_auto_20220408_1630"),
        ("organizations", "0006_remove_organization_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="perimeter_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Sur quel département la structure intervient-elle ?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_department",
                to="geofr.perimeter",
                verbose_name="Département de la structure",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="perimeter_region",
            field=models.ForeignKey(
                blank=True,
                help_text="Sur quelle région la structure intervient-elle ?",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_region",
                to="geofr.perimeter",
                verbose_name="Région de la structure",
            ),
        ),
    ]
