# Generated by Django 4.1.5 on 2023-01-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_organization_favorite_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="imported_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date à laquelle cette organisation a été importée",
                null=True,
                verbose_name="Date de l'import",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_imported",
            field=models.BooleanField(
                default=False,
                help_text="Cette organisation a-t-elle été importée ?",
                verbose_name="Organisation importée ?",
            ),
        ),
    ]
