# Generated by Django 4.1.6 on 2023-02-08 18:54

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_organization_imported_date_organization_is_imported"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="intercommunality_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CC", "Communauté de communes"),
                    ("CA", "Communauté d’agglomération"),
                    ("CU", "Communauté urbaine"),
                    ("METRO", "Métropole"),
                    ("GAL", "Groupe d’action locale"),
                    ("PNR", "Parc naturel régional"),
                    ("PETR", "Pays et pôles d’équilibre territorial et rural"),
                    ("SM", "Syndicat mixte et syndicat de commune"),
                ],
                max_length=5,
                null=True,
                verbose_name="Type d’intercommunalité",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="associations_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre d’associations"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="corporates_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre d’entreprises"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="imported_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date à laquelle cette organisation a été importée",
                null=True,
                verbose_name="Date de l’import",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="inhabitants_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre d’habitants"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="kindergarten_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre d’écoles maternelles"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("commune", "Commune"),
                        ("epci", "Intercommunalité / Pays"),
                        ("department", "Département"),
                        ("region", "Région"),
                        ("special", "Collectivité d’outre-mer à statut particulier"),
                        ("public_org", "Établissement public"),
                        ("public_cies", "Entreprise publique locale (Sem, Spl, SemOp)"),
                        ("association", "Association"),
                        ("private_sector", "Entreprise privée"),
                        ("private_person", "Particulier"),
                        ("farmer", "Agriculteur"),
                        ("researcher", "Recherche"),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Type de structure",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="primary_school_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre d’écoles primaires"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Laisser vide pour autoremplir.",
                verbose_name="Fragment d’URL",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="university_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre d’universités"
            ),
        ),
    ]
