# Generated by Django 4.1.6 on 2023-02-08 14:19

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_organization_intercommunality_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("commune", "Commune"),
                        ("epci", "Intercommunalité / Pays"),
                        ("department", "Département"),
                        ("region", "Région"),
                        ("special", "Collectivité d'outre-mer à statuts particuliers"),
                        ("public_org", "Établissement public"),
                        ("public_cies", "Entreprise publique locale (Sem, Spl, SemOp)"),
                        ("association", "Association"),
                        ("private_sector", "Entreprise privée"),
                        ("private_person", "Particulier"),
                        ("farmer", "Agriculteur"),
                        ("researcher", "Recherche"),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Type de structure",
            ),
        ),
    ]
