# Generated by Django 4.1.5 on 2023-03-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_organization_intercommunality_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="gymnasium_number",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="sports_ground_number",
        ),
        migrations.AddField(
            model_name="organization",
            name="bridge_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de ponts"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="cinema_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de cinéma"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="covered_sporting_complex_number",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de complexes sportifs couverts",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="football_field_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de terrains de football"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="forest_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de forêts"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="nursery_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de crèches"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="other_outside_structure_number",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre de structures extérieures autres",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="protected_monument_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de monuments classés"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="rec_center_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de centres de loisirs"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="running_track_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de pistes d'athlétisme"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="shops_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de commerces"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tennis_court_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Nombre de court de tennis"
            ),
        ),
    ]
