# Generated by Django 4.1.5 on 2023-03-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backers", "0015_backer_perimeter"),
        ("organizations", "0011_remove_organization_gymnasium_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="backer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backers.backer",
                verbose_name="Porteur d'aides",
            ),
        ),
    ]
