project_domain: aides-territoires.beta.gouv.fr
project_version: production
certbot_admin_email: elise.marion@developpement-durable.gouv.fr
certbot_domains: "{{ project_domain }}"
django_settings: core.settings.production
project_env: production
env_file: .env.production
env_target: .env.production
gunicorn_options: ""
shell_prompt: PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
