web: bash scripts/start_web.sh $DJANGO_SETTINGS_MODULE
postdeploy: bash scripts/post_deploy.sh
event: bash scripts/start_celery_event.sh $DJANGO_SETTINGS_MODULE
beat: bash scripts/start_celery_beat.sh $DJANGO_SETTINGS_MODULE
