web: bash scripts/start.sh $DJANGO_SETTINGS_MODULE
postdeploy: bash scripts/post_deploy.sh
worker: DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE celery -A core worker --events --loglevel info
beat: DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE celery -A core worker --beat
