# Generated by Django 2.1.1 on 2018-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(blank=True, help_text='Let it empty so it will be autopopulated.', verbose_name='Slug'),
        ),
    ]
