# Generated by Django 2.1.2 on 2018-11-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bundles', '0002_bundle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together={('owner', 'name')},
        ),
    ]
