# Generated by Django 2.1.4 on 2018-12-19 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0002_bundle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
