---
- name: Collect static
  django_manage:
    command: collectstatic
    app_path: "{{ django_root }}"
    virtualenv: "{{ venv_dir }}"
    settings: "{{ django_settings }}"
  notify: Restart django

- name: Restart django
  become: no
  supervisorctl: name=django state=restarted
  notify: Restart celery

- name: Restart celery
  become: no
  supervisorctl: name=celery state=restarted
