# Generated by Django 2.1.1 on 2018-09-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perimeter",
            name="country",
        ),
    ]
