# Generated by Django 2.1.1 on 2018-09-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0004_auto_20180905_1149"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perimeter",
            name="commune",
        ),
    ]
