# Generated by Django 2.1.1 on 2018-09-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0005_remove_perimeter_commune"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perimeter",
            name="name",
            field=models.CharField(db_index=True, max_length=128, verbose_name="Name"),
        ),
    ]
