# Generated by Django 2.1.1 on 2018-09-05 12:55

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofr', '0005_remove_perimeter_commune'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='perimeter',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='geofr_perim_name_a1369f_gin'),
        ),
    ]
