# Generated by Django 2.1.1 on 2018-09-06 13:23

from django.db import migrations

from geofr.models import Perimeter as _Perimeter
from aids.models import Aid as _Aid


SCALES = _Perimeter.TYPES
PERIMETERS = _Aid.PERIMETERS


def set_perimeters(apps, schema_editor):
    """Set new perimeter field value."""

    Aid = apps.get_model('aids', 'Aid')
    Perimeter = apps.get_model('geofr', 'Perimeter')
    aids = Aid.objects.all()

    europe = Perimeter.objects.get(scale=SCALES.continent)
    france = Perimeter.objects.get(scale=SCALES.country)

    for aid in aids:

        if aid.application_perimeter == PERIMETERS.europe:
            aid.perimeter = europe
        elif aid.application_perimeter == PERIMETERS.france:
            aid.perimeter = france
        elif aid.application_perimeter == PERIMETERS.region:
            region = Perimeter.objects.get(
                scale=SCALES.region,
                code=aid.application_region)
            aid.perimeter = region
        elif aid.application_perimeter == PERIMETERS.department:
            department = Perimeter.objects.get(
                scale=SCALES.department,
                code=aid.application_department)
            aid.perimeter = department
        elif aid.application_perimeter == PERIMETERS.overseas:
            aid.perimeter = france

        aid.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geofr', '0009_auto_20180906_1439'),
    ]

    operations = [
        migrations.RunPython(set_perimeters),
    ]
