# Generated by Django 2.1.1 on 2018-09-18 08:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0010_set_perimeters"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3),
                blank=True,
                null=True,
                size=None,
                verbose_name="Departments",
            ),
        ),
        migrations.AddField(
            model_name="perimeter",
            name="regions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2),
                blank=True,
                null=True,
                size=None,
                verbose_name="Regions",
            ),
        ),
    ]
