# Generated by Django 2.1.1 on 2018-09-18 08:28

from django.db import migrations


def set_regions_departments(apps, schema_editor):
    Perimeter = apps.get_model("geofr", "Perimeter")
    perimeters = Perimeter.objects.all()
    for perimeter in perimeters:
        if perimeter.region:
            perimeter.regions = [perimeter.region]
        if perimeter.department:
            perimeter.departments = [perimeter.department]
        perimeter.save()


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0011_auto_20180918_1027"),
    ]

    operations = [
        migrations.RunPython(set_regions_departments),
    ]
