# Generated by Django 2.1.1 on 2018-09-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0012_update_regions_departments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perimeter",
            name="department",
        ),
        migrations.RemoveField(
            model_name="perimeter",
            name="region",
        ),
    ]
