# Generated by Django 2.2.1 on 2019-09-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0024_create_mainland_overseas_perimeters"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="manually_created",
            field=models.BooleanField(default=False, verbose_name="Manually created"),
        ),
    ]
