# Generated by Django 2.2.5 on 2019-11-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0025_perimeter_manually_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perimeter",
            name="code",
            field=models.CharField(
                help_text="Internal usage only, not relevant for Ad-hoc perimeters",
                max_length=16,
                verbose_name="Code",
            ),
        ),
    ]
