# Generated by Django 2.2.5 on 2021-02-08 15:10

from django.db import migrations, models
from django.contrib.postgres.lookups import Unaccent
from django.db.migrations.operations.special import RunPython
from django.contrib.postgres.lookups import Unaccent


from core.utils import remove_accents


def unaccent_names(apps, schema_editor):
    Perimeter = apps.get_model('geofr', 'Perimeter')
    Perimeter.objects.update(unaccented_name=Unaccent(models.F('name')))


class Migration(migrations.Migration):

    dependencies = [
        ('geofr', '0030_perimeter_is_visible_to_users_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='unaccented_name',
            field=models.CharField(null=True, max_length=128, verbose_name='Name without accent (for indexing purpose)'),
            preserve_default=False,
        ),
        migrations.RunPython(unaccent_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='perimeter',
            name='unaccented_name',
            field=models.CharField(max_length=128, verbose_name='Name without accent (for indexing purpose)')
        )
    ]
