# Generated by Django 2.2.5 on 2021-02-08 15:28

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0031_perimeter_unaccented_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="perimeter",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["unaccented_name"],
                name="unaccented_name_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
