# Generated by Django 3.2.4 on 2021-08-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofr', '0034_cleanup_choices_translations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perimeter',
            old_name='scale',
            new_name='scale_integer',
        ),
        migrations.AlterUniqueTogether(
            name='perimeter',
            unique_together={('scale_integer', 'code')},
        ),
    ]
