# Generated by Django 3.2.12 on 2022-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofr', '0034_cleanup_choices_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='backers_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nombre de porteurs'),
        ),
        migrations.AddField(
            model_name='perimeter',
            name='programs_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nombre de programmes'),
        ),
    ]
