# Generated by Django 3.2.4 on 2021-08-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofr', '0035_start_migrating_scales'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='scale',
            field=models.CharField(choices=[('commune', 'Commune'), ('epci', 'EPCI'), ('basin', 'Bassin hydrographique'), ('department', 'Département'), ('region', 'Région'), ('overseas', 'Outre-mer'), ('mainland', 'Métropole'), ('adhoc', 'Ad-hoc'), ('country', 'Pays'), ('continent', 'Continent')], default='adhoc', max_length=32, verbose_name='Scale'),
            preserve_default=False,
        ),
    ]
