# Generated by Django 3.2.4 on 2021-08-09 10:00

from django.db import migrations


SCALES_DICT = {
    1: 'commune',
    5: 'epci',
    8: 'basin',
    10: 'department',
    15: 'region',
    16: 'overseas',
    17: 'mainland',
    18: 'adhoc',
    20: 'country',
    25: 'continent',
}


def assign_scale(apps, schema_editor):
    Perimeter = apps.get_model('geofr', 'Perimeter')
    for p in Perimeter.objects.all():
        p.scale = SCALES_DICT[p.scale_integer]
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geofr', '0036_perimeter_scale_charfield'),
    ]

    operations = [
        migrations.RunPython(assign_scale, reverse_code=migrations.RunPython.noop)
    ]
