# Generated by Django 3.2.4 on 2021-08-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofr', '0037_assign_scale'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perimeter',
            unique_together={('scale', 'code')},
        ),
        migrations.RemoveField(
            model_name='perimeter',
            name='scale_integer',
        ),
    ]
