# Generated by Django 3.2.15 on 2022-09-20 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0039_auto_20220920_1727"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerimeterData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prop", models.CharField(max_length=100, verbose_name="propriété")),
                ("value", models.CharField(max_length=255, verbose_name="valeur")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "perimeter",
                    models.ForeignKey(
                        help_text="Périmètre pour lequel les données sont importées",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geofr.perimeter",
                        verbose_name="périmètre",
                    ),
                ),
            ],
            options={
                "verbose_name": "donnée de périmètre",
                "verbose_name_plural": "données de périmètre",
                "unique_together": {("perimeter", "prop")},
            },
        ),
    ]
