# Generated by Django 3.2.16 on 2022-12-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "geofr",
            "0040_perimeterdata_squashed_0042_alter_perimeterdata_unique_together",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="population",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="population"
            ),
        ),
    ]
