# Generated by Django 4.1.5 on 2023-01-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0041_perimeter_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="perimeter",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
