# Generated by Django 4.1.5 on 2023-01-19 16:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0041_perimeter_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="coordonnées"
            ),
        ),
    ]
