# Generated by Django 4.1.5 on 2023-01-27 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0042_perimeter_latitude_perimeter_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="projects_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="nombre de projets subventionnés"
            ),
        ),
        migrations.AlterField(
            model_name="perimeterimport",
            name="city_codes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=5),
                help_text="Liste d’identifiants INSEE de communes",
                size=None,
                verbose_name="périmètres contenus",
            ),
        ),
    ]
