# Generated by Django 4.1.8 on 2023-04-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0044_perimeter_density_typology_perimeter_insee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insee_code",
                    models.CharField(max_length=5, verbose_name="code Insee"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Exercice")),
                (
                    "population_strata",
                    models.PositiveSmallIntegerField(verbose_name="Strate population"),
                ),
                ("aggregate", models.CharField(max_length=256, verbose_name="Agrégat")),
                (
                    "main_budget_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valeur de l’agrégat pour le budget principal",
                        max_digits=12,
                        verbose_name="Montant budget principal",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Variable interne OFGL pour data visualisation",
                        null=True,
                        verbose_name="Ordre d’affichage",
                    ),
                ),
                (
                    "perimeter",
                    models.ForeignKey(
                        help_text="Périmètre pour lequel les données sont importées",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geofr.perimeter",
                        verbose_name="périmètre",
                    ),
                ),
            ],
            options={
                "verbose_name": "donnée financière",
                "verbose_name_plural": "données financières",
                "unique_together": {("perimeter", "year", "aggregate")},
            },
        ),
    ]
