# Generated by Django 4.1.7 on 2023-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0044_perimeter_insee_perimeter_siren"),
    ]

    operations = [
        migrations.AddField(
            model_name="perimeter",
            name="density_typology",
            field=models.CharField(
                blank=True,
                help_text="définit le statut d'une commune rurale ou urbaine",
                max_length=50,
                verbose_name="typologie",
            ),
        ),
    ]
