# Generated by Django 4.2.4 on 2023-08-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geofr", "0045_financialdata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perimeterdata",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "donnée de périmètre",
                "verbose_name_plural": "données de périmètre",
            },
        ),
    ]
